### ISSUE TITLE
Add more hover feedback

### ISSUE THREAD

**Issue by developomp** [anyproto/anytype-ts#100]
### Is your feature request related to a problem? Please describe

Some UI elements have no hover feedback whatsoever.

Here is a list of elements with no hover feedback that I could find:

Page icon:
![image](https://github.com/anyproto/anytype-ts/assets/40858122/5b6faf6c-0122-4624-bce2-d05b2fe98b7c)

Sidebar:
![image](https://github.com/anyproto/anytype-ts/assets/40858122/12f9d50f-3830-44be-a8c2-c5a720cd4224)

Sidebar:
![image](https://github.com/anyproto/anytype-ts/assets/40858122/9fe3bf84-1d26-42de-8a10-71ccf274a8b0)

Sidebar:
![image](https://github.com/anyproto/anytype-ts/assets/40858122/f5d6d2e5-9b76-4390-bc59-772b096b8ed8)

Sidebar (edit mode):
![image](https://github.com/anyproto/anytype-ts/assets/40858122/aebd999b-3219-4cd5-9cf6-162b35e25f29)

Space popup:
![image](https://github.com/anyproto/anytype-ts/assets/40858122/bb53e77b-6ea2-47ff-95dc-54d8a94171f2)

Bin:
![image](https://github.com/anyproto/anytype-ts/assets/40858122/b91a5b10-b713-4cec-a40b-0e513cfcf4fc)

Appearance Settings:
![image](https://github.com/anyproto/anytype-ts/assets/40858122/563504f7-296e-43d1-9e5b-30b10d6fbe48)

Toggle Button:
![image](https://github.com/anyproto/anytype-ts/assets/40858122/66670bf9-0307-4416-92eb-d630442e88bb)

About Anytype popup (also missing post-click feedback):
![image](https://github.com/anyproto/anytype-ts/assets/40858122/707b19fc-2c9d-4b43-b9d8-69dcb193f0b2)

### Describe the solution you'd like

Add some sort of hover feedback.

### Describe alternatives you've considered

None

### Additional context

- https://github.com/anyproto/anytype-ts/issues/97#issuecomment-1646947613

### Dependencies

None

---

- [x] I have checked [feature requests](https://community.anytype.io/c/feature-requests/l/latest?board=default) and upvoted existing ones instead of creating a new one (check [this article](https://doc.anytype.io/d/community/community-forum) if you don't know how to join the community)
- [x] I have considered creating a pull request with a new feature instead of a feature request and want to proceed

**Comment by negue** [comment]
Got some more examples:  (sorry missing the cursor above the element in screenshot)

inline block of `@ something`
<img width="146" alt="image" src="https://github.com/anyproto/anytype-ts/assets/842273/a9c7d9ef-1282-4038-b731-17961a02bb96">

relation enum inside table
<img width="178" alt="image" src="https://github.com/anyproto/anytype-ts/assets/842273/04e3a110-2f75-4e71-bb8d-d2f5da8e7de0">

list entry
<img width="464" alt="image" src="https://github.com/anyproto/anytype-ts/assets/842273/11664bc4-f053-469e-9879-a04c9245a7a3">

the checkbox itself
<img width="203" alt="image" src="https://github.com/anyproto/anytype-ts/assets/842273/4c38be9d-7fad-4c3a-a92e-1502ab2ec94c">

the round checkbox
<img width="116" alt="image" src="https://github.com/anyproto/anytype-ts/assets/842273/973f481a-bb9d-4888-80d2-73f58dfceaa1">
