### ISSUE TITLE
After upgrading to 0.43.0 it looks like we lost the library button?

### ISSUE THREAD

**Issue by anschein** [anyproto/anytype-ts#1009]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I can't find the entrance to the library.

### Expected Behavior

Has a function button like the previous version

### Steps To Reproduce

I read the changelog and in the changelog there is a reference to library and bin having a simplified version and being combined with all objects, but I only found bin not library

### Environment

```markdown
- OS:Windows 11
- Version:0.43.0
```

**Comment by ra3orblade** [comment]
Types and relations are now tabs in All Objects: 
<img width="309" alt="Screenshot 2024-10-24 at 16 29 10" src="https://github.com/user-attachments/assets/34b5b924-7687-4523-a85c-08dd5f087bf3">

**Comment by anschein** [comment]
I noticed that I don't have types in these objects that I didn't add to the space, does that mean that there are no more recommended types or relationship objects in the future?
