### ISSUE TITLE
Disable inline LaTeX parsing

### ISSUE THREAD

**Issue by jlhg** [anyproto/anytype-ts#1020]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

I want to use the inline code to display the regexp pattern. However, if the inline text contains two $ symbols, for example, `(^\w+.$)|(^\w+$)`, Anytype will convert it to LaTeX display:

![image](https://github.com/user-attachments/assets/88169b33-1d01-4a8b-b8a0-817c190875e9)

In my opinion, inline code should display raw text instead of formatted text.

Anytype v0.41.1 does not have this problem. I guess it is [a feature added in v0.42](https://community.anytype.io/t/inline-latex-addition/2315).

### Suggested solution

It is better to define another formatting for LaTeX text. The original inline code should display the raw text.

**Comment by ra3orblade** [comment]
By code block you mean inline code?

**Comment by jlhg** [comment]
> By code block you mean inline code?

Yes, sorry for the confusion.

**Comment by ra3orblade** [comment]
https://github.com/anyproto/anytype-ts/pull/1021/files

**Comment by ra3orblade** [comment]
Closing as implemented.
