### ISSUE TITLE
Popup not cleared when setting with local-only network option

### ISSUE THREAD

**Issue by doraeric** [anyproto/anytype-ts#1026]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

In the vault path and network mode configure page, if network is set to local-only, after clicking save button, there will be a confirm popup.

Now there are 2 popups:
- popupSettingsOnboarding
- popupConfirm

After clicked the Yes button, popupSettingsOnboarding is removed from DOM, popupConfirm is invisible but clickable.

If you try to click the `New Vault` button, you will actually click on the Yes button from popupConfirm, so you will click the button twice.

When the Yes button is clicked, `save` is called

https://github.com/anyproto/anytype-ts/blob/2cd8c2fcd9a40c769db31e9bc15379165483b1bc/src/ts/component/popup/settings/onboarding.tsx#L143-L160

line 155 deletes `this.config.userPath`, so in the second time, the path is undefined and you can see the error
```
Error occurred in handler for 'Api': Error: Path must be absolute
```

I think the popup needs to be fixed, and I don't know why line 155 deletes the config.

### Expected Behavior

set network to local-only, select a custom vault path, and then create the vault without error.

### Steps To Reproduce

1. open anytype, logout any valut.
2. open preferences
3. set network to local-only
4. change vault data location to a new path different from now
5. click `save`
6. click `new vault` (it's actually clicking on the `Yes, I accept risks` button), screen not changed
7. click `new vault` again
8. click `get my key`
9. see `failed to create local repo mkdir : no such file or directory` on UI

### Environment

```markdown
- OS: ubuntu 22.04
- Version: 0.43.2
```

**Comment by ra3orblade** [comment]
Fixed
