### ISSUE TITLE
Highlighted items remain after delete

### ISSUE THREAD

**Issue by haron-IV** [anyproto/anytype-ts#1036]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

It is happening in `media` tab, but it looks like a general issue with lists in left sidebar.
Highlight items while holding shift than delete it - items disappear but highlight remains on the other items until you let sidebar fold.

### Expected Behavior

Highlight should reset after delete.

### Steps To Reproduce

1) Go to: All Objects -> Media
2) Select media with shift + mouse click
3) Delete selected items

### Environment

```markdown
- OS: MacOS Sequoia 15.0 (m1 chip)
- Anytype Version: 0.43.4
```

### Anything else?

Screen recording:
https://github.com/user-attachments/assets/a10668b3-04f6-4f9a-94fd-e519d455f559

**Comment by ra3orblade** [comment]
Fixed

**Comment by ra3orblade** [comment]
Closing as completed.
