### ISSUE TITLE
Mermaid does not show text

### ISSUE THREAD

**Issue by uriele** [anyproto/anytype-ts#1067]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Mermaid does not show any text inside the blocks
![image](https://github.com/user-attachments/assets/2bbd152b-15b2-4eef-89f5-08a1924137ef)

### Expected Behavior

I would expect some text inside the foreignObject block
![image](https://github.com/user-attachments/assets/47f59a66-d8ed-4980-8810-17a37caff014)

### Steps To Reproduce

1.  Anytype client 0.43.7
2.  Selfhosted using the latest docker compose image

### Environment

```markdown
- OS: Windows 11
- Version: 26100.2454
```

**Comment by ra3orblade** [comment]
Add chart example please.

**Comment by ra3orblade** [comment]
https://community.anytype.io/t/25400 check this topic pls.

**Comment by uriele** [comment]
Thanks for the link, so apparently it will be fixed in the next version :)

**Comment by ra3orblade** [comment]
> Thanks for the link, so apparently it will be fixed in the next version :)

No, it won't, I've just fixed the original post mermaid code using ChatGPT :) There is nothing to fix.

**Comment by uriele** [comment]
Yeah, you didn't "fix it." I even copied your code, and this is the result.

You cannot "solve with chatGPT" the fact that the text is not written in the `foreignObject` HTML block by modifying the CSS part... I will wait for the update by AnyType, thanks

![image](https://github.com/user-attachments/assets/84ed4d29-3631-452e-a322-c002904afe7c)
