### ISSUE TITLE
Kanban cards don't show Assignee

### ISSUE THREAD

**Issue by mrdrprofuroboros** [anyproto/anytype-ts#1068]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

In kanban view when toggling relations most of them appear on the preview card, but Assignee is not (though is set on the card)

### Expected Behavior

Being able to display Assignee on the kanban preview card

### Steps To Reproduce

- Create a canban table, group by Status
- Create a Task and add an Assignee there
- Open settings -> relations, toggle Assignee relation
- See nothing changes

### Environment

```markdown
- OS: MacOS Sonoma 14.5
- Version: 0.43.7
```

### Anything else?

https://github.com/user-attachments/assets/3868396a-402a-47f5-b012-deef7b931e00

**Comment by ra3orblade** [comment]
You have to add assignee explicitely to the list of relations and turn on the visibilty, these questions should be asked at community.anytype.io.
