### ISSUE TITLE
[Linux] Visible Container Margin  on certain zoom levels

### ISSUE THREAD

**Issue by nihalxkumar** [anyproto/anytype-ts#1074]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

On certain zoom levels all the block (div container) margins are visible. 

https://github.com/user-attachments/assets/2d4c3fcc-7a3a-42e5-8dfc-f3ff51b8e335

### Expected Behavior

If the user hasn't enabled any setting for this then this shouldn't be visible. 

### Steps To Reproduce

`anytype-bin 0.43.8-1` from AUR

### Environment

```markdown
EndeavourOS x86_64
Hyprland
```

**Comment by ra3orblade** [comment]
Found the problem and fixed, thanks!

**Comment by nihalxkumar** [comment]
> Found the problem and fixed, thanks!

Hey @ra3orblade, are the changes pushed? I dont see any update in the AUR.

**Comment by ra3orblade** [comment]
> > Found the problem and fixed, thanks!
> 
> Hey @ra3orblade, are the changes pushed? I dont see any update in the AUR.

AUR package is maintained by community and not officially supported. You can find corresponding topics on forums.

**Comment by nihalxkumar** [comment]
Oh, right. Yes
