### ISSUE TITLE
context menu stuck to "Restore from Bin" option after deleting an object

### ISSUE THREAD

**Issue by auaa-x** [anyproto/anytype-ts#1081]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Move any objects to the bin, and right click on the existing objects, the "Move to Bin" option is updated to "Restore from Bin". There's no effect on clicking the restore option and the option is blocking continuous objects deletion.

### Expected Behavior

"Restore from Bin" option should be "Move to Bin" while the user is not trying to access the objects from Bin. Or something should happen with "Restore from Bin" button.

### Steps To Reproduce

1. Create a new workspace
2. Select "Create from scratch"
3. Enter "All Objects"
4. Checkout "Pages" tab
5. Right click on "Quick Start Guide" and select "Move to Bin"
6. Right click on "Welcome letter", and select "Restore from Bin"

### Environment

```markdown
- OS: macOS 14.5
- Version: 0.43.8
```

### Anything else?

https://github.com/user-attachments/assets/f9cbe2fd-b2ff-433f-8efe-b39a1b05c1cf

**Comment by ra3orblade** [comment]
This is already fixed in current main.

**Comment by ra3orblade** [comment]
Closing as completed.
