### ISSUE TITLE
Appreciation for an Outstanding Project and Team Effort

### ISSUE THREAD

**Issue by n0one42** [anyproto/anytype-ts#1090]
Hello Anytype Team,

I rarely say this, but I am genuinely thankful for this project and the incredible work you all have done. Anytype is a remarkable app that deserves far more attention than it currently gets.

At first glance, the app can seem overwhelming, but that’s only because of the limitless possibilities it offers for structuring information. The only limitation is one’s imagination. In my opinion, it’s a tool where any conceivable structure can be created.

I’m really excited to see how Anytype evolves in the future, and I have no doubt it will continue to grow into something even more amazing.

To me, Anytype and Wiki.js stand out as two of the best tools available, and I deeply appreciate the effort and dedication you’ve put into this project.

Thank you so much for all your hard work!

Warm regards

PS: Nice to see this work made by my homies from Switzerland :)

**Comment by ra3orblade** [comment]
Thanks!

**Comment by uburoiubu** [comment]
thank you!
