### ISSUE TITLE
Misleading README for Installation on macOS

### ISSUE THREAD

**Issue by alessandromrc** [anyproto/anytype-ts#1113]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When we run `./update.sh macos-latest arm64` it fails because for some reason the update.sh script contains this line here: https://github.com/anyproto/anytype-ts/blob/209059527f425f2190aa18d22446029e93c90330/update.sh#L14

It is obviously misleading to people trying to build Anytype without checking the source of the bash file.

![Screenshot 2024-12-21 at 01 18 31](https://github.com/user-attachments/assets/d2ef08bf-3479-40a7-9ab5-7d81d5b66eaf)

### Expected Behavior

I'd expect passing "macos-latest" as an argument to actually work and not fail like it is doing right now.

### Steps To Reproduce

1. Fetch the repo
2. Follow the guide
3. Run `./update.sh macos-latest arm64`

### Environment

```markdown
- OS: macOS Sequoia 15.2
- Version: main branch
```

**Comment by ra3orblade** [comment]
Merged.
