### ISSUE TITLE
Hide "services" menu 

### ISSUE THREAD

**Issue by developomp** [anyproto/anytype-ts#113]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

The [Services](https://developer.apple.com/documentation/appkit/nsapplication/1428608-servicesmenu?language=objc) context menu item is only relevant to MacOS and does nothing on other platform.

![image](https://github.com/anyproto/anytype-ts/assets/40858122/c90e6650-023b-4e62-a408-55ef2804c343)

### Suggested solution

Only show "Services" context menu when on MacOS

### Additional context

Relevant lines of code:
https://github.com/anyproto/anytype-ts/blob/bad413c2efc6cce719aacd792b5dd89815f3eec5/electron/js/menu.js#L36

Also reported here: https://community.anytype.io/t/what-does-the-services-item-do/8952

**Comment by ra3orblade** [comment]
done
