### ISSUE TITLE
AnyType imports json file that doesn't exist

### ISSUE THREAD

**Issue by developomp** [anyproto/anytype-ts#116]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The following line appears to be importing json files that doesn't exist.

https://github.com/anyproto/anytype-ts/blob/bad413c2efc6cce719aacd792b5dd89815f3eec5/src/ts/lib/index.ts#L45

### Expected Behavior

Json files aren't missing.

### Steps To Reproduce

1. Clone this repository
2. Follow the "Running" steps (https://github.com/anyproto/anytype-ts#running)
3. Encounter error

### Environment

```markdown
- OS: Arch Linux Rolling
- Version: bad413c2efc6cce719aacd792b5dd89815f3eec5
```

**Comment by fuksman** [comment]
Hi @developomp, it happens because we started to implement l10n support. 
Please run `npm run update:locale` to download the latest version of localization files. 
We should reflect this in `README.md`. Sorry for the inconvenience.
