### ISSUE TITLE
Light scrollbar on dark theme

### ISSUE THREAD

**Issue by e1sordo** [anyproto/anytype-ts#121]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Hi, team! Currently, the application uses a dark color scheme, which looks fantastic and is easy on the eyes. However, the scroll bar still remains light-colored

### Suggested solution

I am not good at frontend development and in particular at developing desktop applications in Electron, but I found [this answer from user Timmmm](https://stackoverflow.com/questions/65188839/electron-scrollbars-are-not-dark-in-dark-mode), where he suggests two options. I checked only the first of them through developer tools by putting `meta` tag in `head`, and the scrollbar matches the selected color scheme.

### Additional context

Before and after
<img height="300" alt="image" src="https://github.com/anyproto/anytype-ts/assets/16883771/2f3befbf-26e6-46ff-b808-dd7ff97b4faa"><img height="300" alt="image" src="https://github.com/anyproto/anytype-ts/assets/16883771/c4dd24d7-a079-4e0d-9087-9b75a0653b72"><img height="300"  alt="image" src="https://github.com/anyproto/anytype-ts/assets/16883771/ad68785f-594f-4e35-86b8-28764f6a210d"><img height="300" alt="image" src="https://github.com/anyproto/anytype-ts/assets/16883771/9071e14d-26fa-473c-984c-26082a61c64e">

**Comment by twiccox** [comment]
@e1sordo

Actually, they did set a scrollbar thumb color for dark mode, which is `rgba(255,255,255,0.5)`
https://github.com/anyproto/anytype-ts/blob/965b4cce3f8850c440a543b8895ab91520825145/src/scss/theme/dark/common.scss#L26
https://github.com/anyproto/anytype-ts/blob/965b4cce3f8850c440a543b8895ab91520825145/src/scss/theme/dark/common.scss#L377

**Comment by e1sordo** [comment]
@twiccox 

For other operating systems (just tested on Win10), this seems to be enough. And macOS is picky in this regard)

**Comment by xaviibaez** [comment]
I checked it for Linux Ubuntu and seems be working fine 
![image](https://github.com/anyproto/anytype-ts/assets/25080554/98bf55fc-c5da-49b2-8e0e-40defd0bd34e)
![image](https://github.com/anyproto/anytype-ts/assets/25080554/8acc3a72-65fc-4633-87dc-705d06202bdc)
 Also it changes automatically on swiching from light to dark mode :)

**Comment by ra3orblade** [comment]
MacOS shows different scrollbars in overflow elements and normal body, so this setting is not working.

**Comment by ra3orblade** [comment]
This is rather a bug then a feature and it's already in our internal tracker, the priority is low however because I do not have any idea how to fix this in an easy way.

**Comment by arielgmelo** [comment]
This bug still happening
![Screen Shot 2024-11-15 at 11 55 24](https://github.com/user-attachments/assets/956d113e-30f4-47fa-a194-89f23cfcdd12)

**Comment by nanai10a** [comment]
```css
html.themeDark {
  scrollbar-color: var(--color-control-inactive) var(--color-bg-primary);
}
```

My solution which's the simplest custom CSS is here. If encountered same problem on macOS, try this! (no detailed testings has been performed)

---

@ra3orblade I replaced `platformMac` with `platformWindows` in `<html>` on macOS. Then it seems to have solved the scrollbar problem without custom CSS above (but encountered other problems of course). Is this issue still to be not able to fix by external reasons?
