### ISSUE TITLE
The latest main branch fails to run

### ISSUE THREAD

**Issue by developomp** [anyproto/anytype-ts#133]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The latest `main` branch (1d0c1b5f511072d9856c2977bd4a01116cdee146) fails to run with the following error:

```
~/Documents/projects/anytype/anytype-ts ❯ SERVER_PORT=3000 ANYPROF=:6060 npm run start:dev

> anytype@0.33.4-alpha start:dev
> npm-run-all --parallel start:watch start:electron-wait-webpack


> anytype@0.33.4-alpha start:watch
> cross-env-shell webpack-dev-server --progress --mode=development --node-env=development  --env SERVER_PORT=$SERVER_PORT --env DATA_PATH=$DATA_PATH --history-api-fallback --cache


> anytype@0.33.4-alpha start:electron-wait-webpack
> cross-env-shell wait-for-localhost $SERVER_PORT && npm run electron

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
<i> [webpack-dev-server] Content not from webpack is served from '/home/pomp/Documents/projects/anytype/anytype-ts/dist' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
<i> [webpack-dev-middleware] wait until bundle finished: /
94% sealing after seal(node:244704) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'reduce' is deprecated)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:244704) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
asset main.js 26.2 MiB [emitted] (name: main) 1 related asset
runtime modules 27.8 KiB 15 modules
orphan modules 38.7 KiB [orphan] 9 modules
modules by path ./node_modules/ 9.56 MiB 1538 modules
modules by path ./src/ 4.5 MiB
  javascript modules 3.88 MiB 1117 modules
  json modules 629 KiB
    ./src/json/constant.json 7.14 KiB [built] [code generated]
    + 9 modules
modules by path ./dist/ 9.26 MiB
  modules by path ./dist/img/icon/ 37.8 KiB 34 modules
  modules by path ./dist/font/ 1.94 MiB 12 modules
  modules by path ./dist/lib/ 7.28 MiB 8 modules
+ 6 modules

ERROR in /home/pomp/Documents/projects/anytype/anytype-ts/src/ts/lib/api/command.ts
./src/ts/lib/api/command.ts
[tsl] ERROR in /home/pomp/Documents/projects/anytype/anytype-ts/src/ts/lib/api/command.ts(1626,33)
      TS2339: Property 'ListSetObjectType' does not exist on type 'typeof Object'.
 @ ./src/ts/lib/index.ts 4:0-35 55:0-301
 @ ./src/ts/app.tsx 11:0-197 183:4-5 184:4-5 185:4-14 186:4-12 187:4-12 188:4-14 189:4-12 190:4-13 191:4-14 192:4-12 193:4-12 194:4-11 195:4-11 196:4-13 197:4-14 198:4-10 288:8-23 289:8-23 290:8-21 292:8-21 298:38-49 300:12-23 300:42-57 303:8-22 307:8-19 308:8-19 309:8-19 309:43-59 310:8-19 311:8-19 312:8-19 313:8-19 314:8-19 315:8-19 316:8-19 317:8-19 318:8-19 319:8-19 320:8-19 321:8-19 322:8-19 323:8-19 324:8-19 326:12-26 328:8-19 335:8-19 347:26-37 348:25-36 355:8-22 358:12-26 374:16-38 376:20-42 377:20-35 385:20-40 394:16-29 406:26-37 407:23-34 414:12-25 415:12-26 420:12-28 423:12-26 429:50-71 435:28-46 445:46-55 452:8-28 459:23-32 460:22-31 461:29-38 462:28-37 464:20-33 467:20-33 481:23-32 482:22-31 483:29-38 484:28-37 486:20-33 489:20-33 503:23-32 504:22-40 504:41-50 505:29-38 520:23-32 521:22-40 521:41-50 522:29-38 523:28-37 525:20-33 528:20-33 536:20-38 536:70-83 536:107-120 548:8-35 550:23-41 551:35-46 553:20-34 555:54-63 558:29-56 562:29-56 567:24-35 572:36-60 578:36-49 584:36-49
 @ ./src/ts/entry.tsx 3:0-24 4:36-39

webpack 5.88.2 compiled with 1 error in 31206 ms
```

### Expected Behavior

The app launches without error

### Steps To Reproduce

1. Follow the steps in [Building From Source](https://github.com/anyproto/anytype-ts#building-the-source)
2. Observe error

### Environment

```markdown
- OS: Arch Linux Rolling
- Version: 1d0c1b5f511072d9856c2977bd4a01116cdee146
```

**Comment by ra3orblade** [comment]
Protobuf in latest middleware release is outdated, in order to launch current main you have to build anytype-heart from current main branch as well. If you use latest release via update.sh the only option is to switch to the corresponding tag on client.

**Comment by Shampra** [comment]
@ra3orblade Would you know if a release of anytype-heart is planned soon?
(because I have a feeling I'm going to spend a lot of time getting there if I do... if a release is coming soon, I might as well wait a bit ;-))
If you don't know or it won't be "soon", don't worry, I'll get to it when I can.

**Comment by developomp** [comment]
Is there any reason you're waiting for a release? You can always compile [`anytype-heart`](https://github.com/anyproto/anytype-heart) yourself.

**Comment by Shampra** [comment]
I wanted to work on anytype-ts but I came across the problem raised above.
And I don't have the working environment to compile anytype-heart myself. I work under Windows, including for anytype-ts (VM created under Windows) and there is an error when compiling, related to an element not present under a Windows environment :
`cmd\grpcserver\grpc.go:85:83: undefined: syscall.SIGUSR1
 cmd\grpcserver\grpc.go:247:21: undefined: syscall.SIGUSR1
`

Recreating a Linux environment withthe necessary stuff and configuration and... is going to take up a lot of my free time (especially for someone not used to it)... for maybe nothing if you release AT-heart soon ;-). I prefer to keep this free time to help where I can.
Especially since I don't think I can help with Anytype-heart, so I don't need a dev and test environment for it.

Anyway, I can wait. But if it's not scheduled for several weeks, my fingers will be itching 😁.
