### ISSUE TITLE
Object template not applied when creating an object from within the same object

### ISSUE THREAD

**Issue by denis-ev** [anyproto/anytype-ts#163]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I'm uncertain whether this is a bug or a feature...

Initially, I designed a template for the Human object and proceeded to create multiple instances of Humans using this template. However, to my surprise, I discovered that I could create an object from the very object I was editing by simply selecting the text, right-clicking, and choosing the "turn into object" option (I'm new to this, haha).

In my specific situation, I attempted to create another Human using this method, only to realize that the template wasn't being utilized as intended.

### Expected Behavior

I strongly believe that when creating objects in this manner, the template should be automatically applied, particularly in cases where the object being created originates from the same object that utilizes the template. This would ensure consistency and maintain the intended design and functionality of the template.

### Steps To Reproduce

To reproduce the issue, please follow these steps:

1. Begin by creating a template for the Human object.
2. Proceed to create multiple instances of Humans using this template.
3. Next, while editing one of the Human objects, select the desired text and right-click on it.
4. From the context menu, choose the "turn into object" option.
5. Upon creating the object in this manner, you will notice that it does not adhere to the template as expected.

By following these steps, you will encounter the situation where creating a Human object from the currently edited object does not utilize the intended template.

### Environment

```markdown
- OS:macOS 13.4
- AnyType Version: 0.33.3
```

**Comment by Shampra** [comment]
Pretty much the same problem as described here (but created via a different location)
https://community.anytype.io/t/template-not-used-as-default-in-custom-type/10145/5

**Comment by ra3orblade** [comment]
This is fixed in current main/latest alpha/beta builds.
