### ISSUE TITLE
Request to add font settings in client

### ISSUE THREAD

**Issue by wxrl** [anyproto/anytype-ts#167]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

It would be nice to add font settings in the anytype client as especially on Windows, the auto deployed system font settings (usually cannot/hard to change on Windows) when meeting CJK contents are disaster...

### Suggested solution

Add font setting menu as in Firefox for different languages.

**Comment by ra3orblade** [comment]
Please create a feature request at community.anytype.io.
