### ISSUE TITLE
Picture download and text copy in Locked Pages

### ISSUE THREAD

**Issue by wxrl** [anyproto/anytype-ts#168]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Currently, in locked pages, you cannot download pictures (no download button appearing) or copy text (no matter using right click mouse or Ctrl-C)

### Expected Behavior

Per my understanding, locking a page is mainly for avoiding mis-editing, but the "read" permission (which includes download and text copy) shall be fully supported. 

### Steps To Reproduce

1. Create a page with text and pictures uploaded.
2. Lock the page.
3. No download button appears when mouse hovering on the picture or right clicking.
4. Select text, Ctrl-C and Ctrl-V (at some other app) doesn't work. (No text copy menu when right clicking the mouse either.)
5. Unlock the page, and you can download and copy text.

### Environment

```markdown
- OS: Windows 11 & Linux (Debian 12)
- Version:
```

**Comment by ra3orblade** [comment]
You can copy text, show some examples pls.

**Comment by ra3orblade** [comment]
Download button is fixed by https://github.com/anyproto/anytype-ts/commit/7a1ed02d53c5aebf1dc7a219635c0e36b74cffb4

**Comment by wxrl** [comment]
> You can copy text, show some examples pls.

Umm...It seems that was a false alarm. Sorry for that. Ctrl-C & Ctrl-V worked in Locked Pages as well.

While, it would be nice to have Copy and Paste items in both styles of Menu after text selecting and mouse right clicking as shown in the attached pictures.

![Screenshot 1](https://github.com/anyproto/anytype-ts/assets/81678209/527c5d37-b516-4d58-984a-64eb0ba3191c)

![Screenshot 2](https://github.com/anyproto/anytype-ts/assets/81678209/9b7d2079-0618-4636-8ea4-f64d299ad2fc)
