### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by zxiilw63** [anyproto/anytype-ts#170]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Show export error as import in the menu
<img width="1034" alt="SCR-20230809-bvcx" src="https://github.com/anyproto/anytype-ts/assets/133522304/01d20565-650a-46a3-87ec-cff39c39cd28">

### Expected Behavior

Second "导入“ Should be "导出"

### Steps To Reproduce

1. File menu
2. export

### Environment

```markdown
- OS:macOS 14
- Version:0.33.9
```

**Comment by ra3orblade** [comment]
You can fix it in the [Crowdin](https://crowdin.com/project/anytype-desktop) project.
