### ISSUE TITLE
Menu bar looks weird on non-macOS

### ISSUE THREAD

**Issue by liferooter** [anyproto/anytype-ts#183]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Menu bar looks weird with the app since global application menu is not always there, so it's integrated with the application window. Also Electron is far from perfect and doesn't support dark color schemes well, so I end up with following UI on my pretty default Fedora with GNOME setup:

![image](https://github.com/anyproto/anytype-ts/assets/54807745/ca994395-68ec-49d3-a36b-0a79285c973a)

### Suggested solution

There are a wide range of possible solutions:
1. Remove menu bar at all on non-macOS platforms. Seriously. Menu bar is an ancient UI pattern that is thrown away everythere. On macOS it's replaced with global menu bar, but on other platforms it looks like a part of your application is from 1990th. Use different UI elements on non-macOS. I know, the main feature of cross-platform UI engines like Electron is the ability not to do different UI for different platforms, but now it looks good only on one platform.
2. Do something to make Electron follow your dark theme. It's a hack and partial solution, but this will make menu bar look at least not so ugly.
3. Allow to disable menu bar. It won't make it less ugly, but at least will allow user not to see it most of time.

**Comment by Majoramari** [comment]
It's also their on windows and looks as bad as on linux

**Comment by sirito97** [comment]
The best thing is to have a choice to remove both menu bar and title bar like what I did here, I can resize it too and it looks really clean.
![image](https://github.com/anyproto/anytype-ts/assets/66971290/9ca6d740-38a1-403b-8ffe-024822b5abdd)

**Comment by aadilayub** [comment]
We could also add the option to draw custom window decorations, like Logseq does it (and I think Obsidian as well):

![image](https://github.com/anyproto/anytype-ts/assets/31581044/71ebc2c5-67a0-4168-aeca-c218abff7562)

**Comment by astrocaat** [comment]
Absolutely agree, it looks horrible! Until a better UI gets implemented, at least give us the possibility to show/hide it with a shortcut, like Notion already does.

**Comment by sirito97** [comment]
> Absolutely agree, it looks horrible! Until a better UI gets implemented, at least give us the possibility to show/hide it with a shortcut, like Notion already does.  

there was already a pull request that adds this but got rejected.

**Comment by astrocaat** [comment]
That's a shame. Until it gets implemented, I'll go back to Notion then. At least it looks a bit more nice and native on my Linux desktop.

**Comment by elkhaligy** [comment]
This is already implemented!
![image](https://github.com/anyproto/anytype-ts/assets/66971290/4af3c8dd-89b3-4269-a51a-c979ee6a867d)
