### ISSUE TITLE
Give clickable elements a pointer cursor

### ISSUE THREAD

**Issue by A-delta** [anyproto/anytype-ts#192]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [x] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Not sure if this is a bug or not. Using Anytype, I have trouble knowing if clicking on something will take me elsewhere or will open something because the cursor doesn't change its form:
![image](https://github.com/anyproto/anytype-ts/assets/55986107/48f72e3c-7309-4ec6-91d9-fec82ad33c9d)

### Suggested solution

Change cursor when hovering a clickable element (that will open a new page for example)

### Additional context

 I installed Anytype through [this](https://search.nixos.org/packages?channel=23.05&show=anytype&from=0&size=50&sort=relevance&type=packages&query=anytype) package using Home Manager on NixOS so it could come from there.
But since the cursor *can* change ![image](https://github.com/anyproto/anytype-ts/assets/55986107/1d64086c-9bfa-41ba-932b-a864c9df5ee4), I figured it was not a bug.

**Comment by negue** [comment]
This was mentioned twice #97 and #100 - this was the latest response

> Thank you for highlighting this. As noted in a previous issue, our strategy is to provide a more native experience rather than a web-like one. However, we also recognize the importance of creating an interface that feels interactively responsive. This calls for a systematic approach, ensuring each element is addressed in its specific context. We'll engage with the design team to determine how best to integrate this into our design system and identify necessary adjustments

_Originally posted by @sebyakin in https://github.com/anyproto/anytype-ts/issues/100#issuecomment-1652075428_

Maybe future revisions will have this fixed / improved :)

**Comment by fuksman** [comment]
@any contributor @negue community
