### ISSUE TITLE
Unable to create Audio Object

### ISSUE THREAD

**Issue by larrydewey** [anyproto/anytype-ts#195]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When attempting to create a set of `Audio` type, there is no option to add anything:

![anytype-audio-issue](https://github.com/anyproto/anytype-ts/assets/41640198/ef1e5ec3-a7fa-494d-878c-4d3e3c0b1d77)

Further, when attempting to create a new instance of type `Audio`, it is not possible:

![anytype-audio-issue-2](https://github.com/anyproto/anytype-ts/assets/41640198/a6214768-2943-448d-8efe-40aad5074fe2)

### Expected Behavior

The ability to add an instance of the type; either within the context of a set, or from the global creation screen.

### Steps To Reproduce

1. Create a new set of Object type: `Audio`

OR

1. Create a new Object and attempt to select the `Audio` type.

### Environment

```markdown
- OS:Linux - Fedora 38 
- Version: 0.33.3
```

### Anything else?

I attached images in the current behavior.

**Comment by ra3orblade** [comment]
You can create audio object only by uploading audio files to editor.
