### ISSUE TITLE
Exporting to pdf removes tabs

### ISSUE THREAD

**Issue by stefanfusko** [anyproto/anytype-ts#206]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When I try to export to pdf, Anytype removes tabs. As you can see in my screenshots.

### Expected Behavior

The tabs should be visible

### Steps To Reproduce

1. Create new page
2. Indent line with Tab key
3. Export page (printing does also remove indentation)

### Environment

```markdown
- OS:Windows 10
- Version: 0.34.3
```

### Anything else?

Screenshot from Anytype:
![image](https://github.com/anyproto/anytype-ts/assets/47608745/eb0b632d-89e7-4833-bf0b-b2295da943a1)

Screenshot from pdf viewer: 
![image](https://github.com/anyproto/anytype-ts/assets/47608745/f8e01da1-d7ca-460d-b3ce-1bd8218b053e)

**Comment by ra3orblade** [comment]
This is a known issue, will be fixed.
