### ISSUE TITLE
Theme doesn't change as per system

### ISSUE THREAD

**Issue by warmachinesocial** [anyproto/anytype-ts#208]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Theme doesn't change as per system preferences in Fedora 38 with Gnome

### Expected Behavior

To auto change when darkStyle is toggled on or off

### Steps To Reproduce

1. Change the setting to system under appearance
2. Toggle on or off the darkStyle in Gnome Appearance
3. Check the effect to the app

### Environment

```markdown
- OS: Linux
- Version: Fedora 38 with Gnome
```

**Comment by ra3orblade** [comment]
https://www.reddit.com/r/gnome/comments/12n408y/electron_apps_dont_seem_to_follow_dark_theme/
