### ISSUE TITLE
Severe Memory Leak: Anytype client fills RAM completely

### ISSUE THREAD

**Issue by bannert1337** [anyproto/anytype-ts#209]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When creating a new custom `Type` the unfolded list box displays all current `Types` available. After typing the name for a custom `Type` the unfolded list box shows a loading animation. This is enough to make my Laptop's fans spin up and when looking into Task Manager, the Anytype client takes all available RAM. This causes the system to slow down severely and will take some time to revert. After the search is finished, the client still takes up a lot of RAM.
I have 64 GB of RAM installed on my system. After searching, the process `anytypeHelper.exe` still takes up ~30 GB of RAM. While searching, the process takes 54 GB of RAM and produces ~70-80% of CPU usage.
I know that a bug report about a memory leak is already open, but I wasn't able to find a register function for the Anytype community forum.

### Expected Behavior

The client should only take up a minimum amount of RAM and CPU usage.

### Steps To Reproduce

1. Open Anytype client
2. Click Library
3. Focus the search field
4. Enter a name

### Environment

```markdown
Edition	Windows 11 Pro
Version	22H2
Installed on	‎23.‎02.‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0
Device name	DESKTOP-8P8SG47
Processor	AMD Ryzen 5 5600H with Radeon Graphics 3.30 GHz
Installed RAM	64.0 GB (62.9 GB usable)
Device ID	8F896C85-ED23-417E-BC54-90FBE1EBFB70
Product ID	00330-80000-00000-AA334
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Device: DESKTOP-8P8SG47
OS version: win32 x64 10.0.22621
App version: 0.34.3
Build number: build on 2023-08-16 11:07:20 +0000 UTC from  at #2815587c8afa3f81e75336226cacecb7fe105e9c(v0.27.21)
Library version: v0.27.21
Account ID: A6RddMdCq3c4yfsVSYhsVBu2FYEBoGUJze5r3LHfgoMdQdHp
Analytics ID: a614454c-efcd-4ee0-b995-6c1d38c157cd
Device ID: 12D3KooWRrC9GjVBLgAXo9x2dVHqKYKKJKE9wqwS3JAow9k8LY69
```

### Anything else?

[Profile-20230819T135233.zip](https://github.com/anyproto/anytype-ts/files/12385767/Profile-20230819T135233.zip)

**Comment by ra3orblade** [comment]
It does not reprduce for me but I believe it's connected with recursive middleware requests, could you please open devtools and reproduce the bug with Debug -> Flags -> Middleware turned on.

**Comment by bannert1337** [comment]
I tried again and set the flag `Middleware`. CPU and RAM usage already goes through the roof. 
[Profile-20230822T072622.zip](https://github.com/anyproto/anytype-ts/files/12406051/Profile-20230822T072622.zip)
Searching takes a very long time. Often can't find objects with the exact same name. 
Network recording while searching:
[search.zip](https://github.com/anyproto/anytype-ts/files/12406073/search.zip)
This is a recording of my task manager:
![explorer_BmU7ylSnvQ](https://github.com/anyproto/anytype-ts/assets/58707896/622f8d10-987c-4592-85e0-39a9f82688a3)
When I try `File` > `Process debug` this error comes up:
![Anytype_Y398zOBqCx](https://github.com/anyproto/anytype-ts/assets/58707896/fe4ac255-4365-41a5-9841-290925edaea3)
When I try `File` > `Space debug` nothing happens.
When I try `File` > `Current object debug` nothing happens.
All the log files created are empty and have 0 bytes.
Here is a heap snapshot:
[Heap-20230822T074303.zip](https://github.com/anyproto/anytype-ts/files/12406211/Heap-20230822T074303.zip)

**Comment by bannert1337** [comment]
On Arch Linux, the problem is very less severe.

**Comment by bannert1337** [comment]
Since the `anytypeHelper` process causes the CPU and RAM usage, the memory leak is probably in [`anytype-heart`](https://github.com/anyproto/anytype-heart). 
Therefore, I created an additional ticket in the [`anytype-heart`](https://github.com/anyproto/anytype-heart) repository:
https://github.com/anyproto/anytype-heart/issues/332

**Comment by ra3orblade** [comment]
Could you make a screenshot of console with Middleware flag on?

**Comment by bannert1337** [comment]
[Screencast from 2023-08-23 13-10-58.webm](https://github.com/anyproto/anytype-ts/assets/58707896/7c6a23c2-5e34-450a-b456-cddeb3da872b)

**Comment by ra3orblade** [comment]
Thanks, I've added timeout on searching, so this problem should go away.

**Comment by ra3orblade** [comment]
Closed as inactive.

**Comment by NecaX** [comment]
The memory leak is still active. I have a collection with multiple pages and when I load it multiple times, the loading time and the RAM consummed by the application increases.

I attack my technical information.
```
OS version: win32 x64 10.0.26100
App version: 0.46.8
Build number: build on 2025-05-27 16:39:45 +0000 UTC at #7b8dd360f08e3d7aef5d5d94927195ee43625588
Library version: v0.41.0-rc15
Anytype Identity: A7zQJAiv6DRZ2y6tGPqLok2ZvaLRnHzPhqe4wzkT5UWKxQnN
Analytics ID: MauL2NWmXvt4iu3k9mrUywi9q7NdQJPyB4GBCH11BQxpaFKQ
Device ID: 12D3KooWQd4fST9YsrUGAP5mU13Ss2JeS8o8P7X3ox1gtfGZpXcs
Ethereum Address: 0xA11313406Ae13dFb47A54B0146B0EEa252849C3c
```
