### ISSUE TITLE
Allow to unlink an object that is in the bin

### ISSUE THREAD

**Issue by rzelnik** [anyproto/anytype-ts#211]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

If a link points to an object that is in the bin or is non-existent, it is impossible to remove the link without removing the whole text. It just shows "Object is in the bin" or "Non-existent object", but there's no option to unlink them.

### Suggested solution

Users should be able to unlink objects that are in the bin or are non-existent just like existent objects.

### Alternative

Currently I remove links to non-existent objects by replace them with a link to an existent object and then unlink, but this is a redundant step.

**Comment by ra3orblade** [comment]
We will look into that.

**Comment by ignatovv** [comment]
@rzelnik hi there. Could you please try to reproduce the issue in the latest version of the app (at least Version: 0.34.3). And if it is still reproducible for you record a video please 🙏

**Comment by ra3orblade** [comment]
Fixed.
