### ISSUE TITLE
Add mobile and P2P for mobile and desktop

### ISSUE THREAD

**Issue by heapwolf** [anyproto/anytype-ts#216]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

there is no mobile app, plus, p2p would be nice.

### Suggested solution

Would you accept a PR or consider a collaboration for moving from Electron to Socket https://github.com/socketsupply/socket. Socket means one codebase for all major OS's including desktop and mobile. There is no new language to learn like Dart or Rust (here are some [examples](https://github.com/socketsupply/socket-examples/tree/master/socket-features)). It also binds libuv into the javascript environment which makes it possible to do P2P everywhere. Our P2P provides comprehensive NAT traversal and even allows Alice to send messages to Bob when Bob is offline (a use case that I think applies here) We'd be happy to help you get it done.

**Comment by heapwolf** [comment]
hey @fuksman im just curious what made you decide this wasn't worth a conversation :)

**Comment by fuksman** [comment]
@heapwolf, you advertised your project without even checking that we have native mobile apps for both iOS and Android. P2P is an essential part of Anytype as well. What's worth discussing here from your point of view?

**Comment by ra3orblade** [comment]
Sorry, this is not an issue, please move it to discussions.

**Comment by heapwolf** [comment]
> Would you accept a PR or consider a collaboration
@fuksman hey, sorry if it appeared to you as if I were advertising, I considered this more of an offer to contribute code.

I realize you have a mobile app, but as I can see from reading the code it looks like it could be hard to maintain that approach since there is so much platform specific code. Also, Electron is a real beast and there are a lot of valid criticisms from users about binary size, memory footprint, and security. There could be some discussion around improving all of this without too much friction or refactoring. In terms of P2P, I've read your code and I realize you're solving the data replication problem in a really cool way, but may still have unresolved problems in terms of NAT traversal, and relying on server infrastructure. We don't solve the *replication* problem, we solve the *network* problem, so there could also be some discussion around this.

I saw Anytype's public announcement which suggested helping people build p2p software, maybe this is all handled though your no-code UI and you'll just be building this one app, so perhaps I didn't fully understand what you're trying to offer. As @ra3orblade said, maybe we can continue the discussion over on the forums.
