### ISSUE TITLE
Input cursor sometimes jumps one character back while typing

### ISSUE THREAD

**Issue by mrusme** [anyproto/anytype-ts#219]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

On the Mac app, as well as the Linux app (Fedora, AppImage), the input cursor sometimes jumps one character back while typing (e.g. a journal entry), leading to words becoming mangled up:

```
            hello woldr
jumped back here ---^
```

### Expected Behavior

The cursor should act normally.

### Steps To Reproduce

1. Create a new page
2. Write a long text

### Environment

```markdown
- OS: MacOS, Fedora Linux
- Version: 0.34.3
```

**Comment by ra3orblade** [comment]
This is happening because of incorrect subscription to object name and description updates, this commit should fix this https://github.com/anyproto/anytype-ts/commit/1306868e5290d335209f5b80cebe643be11b59c7

**Comment by mrusme** [comment]
I can confirm that with the latest alpha this issue is fixed.
