### ISSUE TITLE
Search Relation result different between : on type object and on relation menu => request for a "political" decision

### ISSUE THREAD

**Issue by Shampra** [anyproto/anytype-ts#220]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

https://community.anytype.io/t/source-relation-for-a-custom-object-type-not-searchable/10594

Library -> custom type -> add relations by in in-page "New"
and
Library -> custom type -> Relations Menu -> add relations by "New" in this popup menu
give different result

### Expected Behavior

It must be the same result because it's always "add relation to my type" for user.

### Steps To Reproduce

Search "Source" with : 
Library -> custom type -> add relations by in in-page "New"
and
Library -> custom type -> Relations Menu -> add relations by "New" in this popup menu

### Environment

```markdown
- OS:Windows
- Version:0.34.3
```

### Anything else?

**In code :**
- type.tsx (in-page "add") -> onRelationAdd is filtered by `recommendedKeys.concat(systemKeys)`
And many relation are excluded.
- view.tsx ("add in relation popup") -> onAdd is filtered by `dbStore.getObjectRelationKeys(rootId, rootId)`
So everything except what is already used by the

**example indicated in the bug ticket :**
**_Source_** relation is used by bookmark, a default AT type.

... and here, it can be a team choice!
- either relations linked to types at the heart of AT must not be used elsewhere
- or it must be possible to do so (even if it means hijacking them, "Source" used for purposes other than a Bookmark will have other uses... and we'll potentially have to take this into account during development)

Please tell me, I haven't made a Pull Request while waiting for confirmation.

**Comment by ra3orblade** [comment]
https://github.com/anyproto/anytype-ts/commit/23d3e7017c926d23bbbf9930303d1a9f22d3c95a
