### ISSUE TITLE
minimizing and maximizing app window causes gallery view distortion

### ISSUE THREAD

**Issue by Raphalue** [anyproto/anytype-ts#222]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [ ] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Upon minimizing and maximizing the app window while in gallery view for a set of items, the gallery view layout breaks, causing items to lose their intended arrangement and alignment.

### Expected Behavior

The gallery view should retain the original layout and alignment

### Steps To Reproduce

1. Open the app and navigate to any set.
2. Set the view to Gallery mode.
3. Minimize the app window or Maximize it. 

### Environment

```markdown
- OS: Windows 11 v22631.2262
- Version: 0.34.3
```

**Comment by ra3orblade** [comment]
Merged, check pls
