### ISSUE TITLE
Conflict issue with anytype rpm release

### ISSUE THREAD

**Issue by warmachinesocial** [anyproto/anytype-ts#242]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When installing the rpm the package it throws an error of conflict

![image](https://github.com/anyproto/anytype-ts/assets/35785259/aee81016-8146-4903-b2af-cda8292e4136)

### Expected Behavior

It should have installed the package

### Steps To Reproduce

1. Download the rpm package
2. Install using terminal to get the error

### Environment

```markdown
- OS:Linux
- Version: Fedora 38
```

**Comment by nishp77** [comment]
The above issues can be resolved by not including build ids
`fpm: ['--rpm-rpmbuild-define "_build_id_links none"']`

**Comment by ra3orblade** [comment]
Its built  with electron-builder. https://github.com/ferdium/ferdium-app/issues/416

**Comment by ra3orblade** [comment]
I've added this to package.json, so you can either build it by urself and check or wait for next alpha build to check.

```https://github.com/anyproto/anytype-ts/commit/1ccc5549e97c488b7c0f0149dd2cf3ad03562ecehttps://github.com/anyproto/anytype-ts/commit/1ccc5549e97c488b7c0f0149dd2cf3ad03562ece```
