### ISSUE TITLE
Building project as per ReadME.md failed

### ISSUE THREAD

**Issue by nishp77** [anyproto/anytype-ts#243]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When running the command `npm install -D` build fails with an error

`➜  anytype-ts git:(main) ✗ npm install -D

> anytype@0.34.4-alpha postinstall
> npx patch-package && electron-builder install-app-deps

patch-package 6.4.7
Applying patches...
keytar@7.7.0 ✔

Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    keytar@7.7.0

  applied to

    keytar@7.9.0
  
  At path
  
    node_modules/keytar

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package keytar

  to update the version in the patch file name and make this warning go away.

---
patch-package finished with 1 warning(s).
  • electron-builder  version=24.6.3
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=keytar@7.9.0 platform=linux arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path /home/joker/Desktop/anytype-ts/node_modules/keytar
    npm ERR! command failed
    npm ERR! command sh -c -- prebuild-install || npm run build
    npm ERR! > keytar@7.9.0 build
    npm ERR! > node-gyp rebuild
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.20.2 | linux | x64
    npm ERR! gyp info find Python using Python version 3.11.4 found at "/usr/bin/python3"
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/home/joker/Desktop/anytype-ts/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/joker/Desktop/anytype-ts/node_modules/keytar/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/joker/Desktop/anytype-ts/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/joker/.electron-gyp/22.0.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/joker/.electron-gyp/22.0.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/joker/Desktop/anytype-ts/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/joker/.electron-gyp/22.0.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/joker/Desktop/anytype-ts/node_modules/keytar',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! Package libsecret-1 was not found in the pkg-config search path.
    npm ERR! Perhaps you should add the directory containing `libsecret-1.pc'
    npm ERR! to the PKG_CONFIG_PATH environment variable
    npm ERR! Package 'libsecret-1', required by 'virtual:world', not found
    npm ERR! gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    npm ERR! gyp ERR! configure error 
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/joker/Desktop/anytype-ts/node_modules/node-gyp/lib/configure.js:261:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
    npm ERR! gyp ERR! System Linux 6.4.11-200.fc38.x86_64
    npm ERR! gyp ERR! command "/home/joker/.nvm/versions/node/v16.20.2/bin/node" "/home/joker/Desktop/anytype-ts/node_modules/.bin/node-gyp" "rebuild"
    npm ERR! gyp ERR! cwd /home/joker/Desktop/anytype-ts/node_modules/keytar
    npm ERR! gyp ERR! node -v v16.20.2
    npm ERR! gyp ERR! node-gyp -v v9.0.0
    npm ERR! gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/joker/.npm/_logs/2023-08-31T14_37_11_154Z-debug-0.log
    
                    command=/home/joker/.nvm/versions/node/v16.20.2/bin/node /home/joker/.nvm/versions/node/v16.20.2/lib/node_modules/npm/bin/npm-cli.js rebuild keytar@7.9.0
                    workingDir=
npm ERR! code 1
npm ERR! path /home/joker/Desktop/anytype-ts
npm ERR! command failed
npm ERR! command sh -c -- npx patch-package && electron-builder install-app-deps

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joker/.npm/_logs/2023-08-31T14_37_05_918Z-debug-0.log`

### Expected Behavior

Should install node modules 

### Steps To Reproduce

1. Just clone the project
2. Run the command as per README.md

### Environment

```markdown
- OS:Linux
- Version:Fedora 38
```

**Comment by ra3orblade** [comment]
It says to install libsecret as a dependency.

**Comment by nishp77** [comment]
Yes I had installed the dependency but keytar module has some issue I think

**Comment by nishp77** [comment]
Plus you're not correct regarding the package to be installed as per README.md it has to `sudo dnf install libsecret-devel` 
For reference:- https://www.npmjs.com/package/keytar

I did install this package but it wasn't working.

**Comment by nishp77** [comment]
I have resolved this issue just now it was missing g++ as dependency for keytar module. So you could update your README.md
`sudo dnf install g++`
