### ISSUE TITLE
Autocompletion/autocorrection not working on Android and Linux

### ISSUE THREAD

**Issue by mrusme** [anyproto/anytype-ts#269]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

While typing on an Android device the swiping functionality of the keyboard won't work. Similarly the device won't suggest next words to type, and its autocorrection feature won't work.

On Linux the autocorrection doesn't work either.

### Expected Behavior

The editor should behave like every other input field, allowing for the keyboard to use swiping/text suggestions and autocorrection.

### Steps To Reproduce

1. Create a new document on Android
2. Activate a keyboard that supports autocompletion and/or swiping
3. Type

### Environment

```markdown
- OS: Android, Linux
- Version: 0.34.3
```

**Comment by ra3orblade** [comment]
Why do you create Android issues in a desktop repository?
