### ISSUE TITLE
Sidebar Clipping

### ISSUE THREAD

**Issue by kekuwi** [anyproto/anytype-ts#283]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Texts and Buttons are clipping out of the sidebar window when minimized.

### Expected Behavior

not having texts and buttons clipping through the sidebar window

### Steps To Reproduce

1. minimize the sidebar by sliding it all the way to the left.

### Environment

```markdown
- OS:Windows 10
- Version: 22H2 (x64)
- Anytype Version: 0.34.5-alpha
```

### Anything else?

https://github.com/anyproto/anytype-ts/assets/132612495/a974dc5b-5ecf-4ddc-a5ae-84ee16f9a652

(sorry for the watermark)

**Comment by ra3orblade** [comment]
This is fixed in main.
