### ISSUE TITLE
Cant "Check for Update" on Kubuntu 22.04

### ISSUE THREAD

**Issue by ZachariasFrings** [anyproto/anytype-ts#284]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Nothing happens after clicking the button.
No Message or else is displayed

### Expected Behavior

Anytype Checks for latest updates and asks to install them

### Steps To Reproduce

1. Click "Anytype"
2. Click "Check for updates"

### Environment

```markdown
- OS:Kubuntu 22.04lts
- Version: Anytype Version 0.33.3/0.34.4
```

### Anything else?

I had to manually remove version 0.33.3 and install the the new 0.34.3.
The bug persists in the newer version aswell

**Comment by ra3orblade** [comment]
This is electron-updater restriction, auto-update only works in AppImage on Linux.
