### ISSUE TITLE
[macOS] Typing moves the cursor before the letter

### ISSUE THREAD

**Issue by dminca** [anyproto/anytype-ts#287]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

* typing breaks cursor movement intermittently

during typing, the cursor is moved before the written letter

### Expected Behavior

* typing should continue letter after letter without moving before the typed letter

### Steps To Reproduce

1. open MacOS AnyType app
2. create a Page
3. write something in it (anywhere)

### Environment

```markdown
- OS: macOS 13.5.2
- Version: Version: 0.34.3
```

### Anything else?

https://github.com/anyproto/anytype-ts/assets/5355219/cef7c0b4-6323-46a8-812b-0328bb59be7b

**Comment by ra3orblade** [comment]
This is already fixed in `main`. https://community.anytype.io/t/cursor-jumping-back-while-typing-still-a-problem/10562/23
