### ISSUE TITLE
aarch64 release

### ISSUE THREAD

**Issue by Eloitor** [anyproto/anytype-ts#291]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

I want to be able to run anytype on my pinephone.

### Suggested solution

Release aarch64 Appimage.

**Comment by ra3orblade** [comment]
duplicate https://github.com/anyproto/anytype-ts/issues/83
