### ISSUE TITLE
Anytype messes with ~/.config/mimeapps.list

### ISSUE THREAD

**Issue by pshirshov** [anyproto/anytype-ts#292]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Every time I start Anytype it overwrites ~/.config/mimeapps.list in order to add 

```
[Default Applications]
x-scheme-handler/anytype=anytype.desktop
```

Even if that entry is already there, it still overwrites the file.

YOU MUST NEVER DO IT. IT BREAKS HOME MANAGER!

### Expected Behavior

Anytype (and any other applications) MUST NEVER DO ANY VOLUNTARY UPDATES to the default applications list.

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### Anything else?

STOP DOING THAT

**Comment by pshirshov** [comment]
For some mysterious reasons I have tens of Electron apps but only anytype does that.

**Comment by kseistrup** [comment]
> For some mysterious reasons I have tens of Electron apps but only anytype does that.

Same here. Every time I start AnyType, it sets itself as the default browser.
