### ISSUE TITLE
Inline math equations

### ISSUE THREAD

**Issue by Eloitor** [anyproto/anytype-ts#297]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

It would be nice if I could add math in a middle of a sentence, just like this $x^2$.

### Suggested solution

Allow latex equations to be changed from "display mode" (in its own line) to "inline mode" (in the middle of text).

**Comment by Eloitor** [comment]
Related to this, I would also like formulas in "display mode" to default to centered. Could you consider adding an option for that?

**Comment by solfrak** [comment]
We could use the englobe the equation in $ character similar to notion

**Comment by PeterWang-dev** [comment]
A core need for note. Hope this can be implemented.

**Comment by nicocossiom** [comment]
This is a very much needed improvement. Using Anytype to take notes that require any type of math notation is suboptimal due to this. Hopefully it can get up there in the upcoming features soon, it's quite the deal breaker for some people.

**Comment by zulee1711** [comment]
I have this feature that can be implemented as well. Math notation is a huge part of my note, and with only regular equation, I cannot do much

**Comment by Devanarayanan2205** [comment]
You can use this website and copy past the math in anytype
![image](https://github.com/anyproto/anytype-ts/assets/153890649/13205fa1-7e68-4228-ad4a-b5344f6e4ba3)
![image](https://github.com/anyproto/anytype-ts/assets/153890649/a0de576c-5b3f-4b4d-9c9c-b36ca94e4f9b)

**Comment by mathikas** [comment]
definitely this, please also support Microsoft Word-math typing style, it's much faster than traditional LaTeX

**Comment by ra3orblade** [comment]
Closing as implemented https://github.com/anyproto/anytype-ts/pull/368, available in this version https://github.com/anyproto/anytype-ts/releases/tag/v0.41.44-beta
