### ISSUE TITLE
any convenience for daily note with calendar

### ISSUE THREAD

**Issue by chinarma** [anyproto/anytype-ts#298]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

any basic idea of anytype  is wonderful , but front platform   （like  daily note） is not  convenience.

### Suggested solution

some  calendar note function as Capacities is suggest.

**Comment by ra3orblade** [comment]
Calendar view is implemented in sets, next updates will bring weekly and yearly view for the calendar, widget calendar and timeline.
