### ISSUE TITLE
Page is shifted to left when opening an object

### ISSUE THREAD

**Issue by elkhaligy** [anyproto/anytype-ts#301]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

when you press on any object, the page shifts a little to the left as it is shown in the given videos.

### Expected Behavior

page shouldn't shift like what is in the videos

### Steps To Reproduce

create a set of objects, create an object and open it.

### Environment

```markdown
- OS:Windows 11
- Version: 0.35
```

### Anything else?

https://github.com/anyproto/anytype-ts/assets/66971290/9abb6a01-9206-4ed4-8ebd-82c121d07b24

https://github.com/anyproto/anytype-ts/assets/66971290/87d19460-7b13-4d02-9792-0a6df42c39a4

**Comment by sirito97** [comment]
I just noticed that the same thing happens when
1. Openning search (ctrl+s)
2. Space settings
3. Account settings
So basically any popup will case this

**Comment by AFreeBaldy** [comment]
Hey is anyone working on this? I can work on fixing it

**Comment by sirito97** [comment]
> Hey is anyone working on this? I can work on fixing it

I don't think, go ahead please.

**Comment by AFreeBaldy** [comment]
![image](https://github.com/anyproto/anytype-ts/assets/115787932/c3f05176-1ec7-427f-ab3f-86be6b336807)
Im pretty sure this is the cause if it, I am going to remove it then submit a pull request

**Comment by AFreeBaldy** [comment]
@ra3orblade Hey does this repository actually take pull request, or is it an independent company who just happen to open source their code

**Comment by fuksman** [comment]
> @ra3orblade Hey does this repository actually take pull request, or is it an independent company who just happen to open source their code

Yes, we welcome pull requests and assistance from contributors. For more information, please visit https://github.com/anyproto/.github/blob/main/docs/CONTRIBUTING.md#contributing-code.

**Comment by AFreeBaldy** [comment]
hey it seems like the shifting effect was added intentionally? should i submit a pull to remove it, as its kinda unnecessary to pad it. maybe it was but there by accident @fuksman

**Comment by sirito97** [comment]
> ![image](https://user-images.githubusercontent.com/115787932/272538626-c3f05176-1ec7-427f-ab3f-86be6b336807.png) Im pretty sure this is the cause if it, I am going to remove it then submit a pull request

I just tested this and yes this is the problem, nice find! it is consistent now, thank you.

**Comment by elkhaligy** [comment]
> hey it seems like the shifting effect was added intentionally? should i submit a pull to remove it, as its kinda unnecessary to pad it. maybe it was but there by accident @fuksman

are you gonna make a pull request for this change or?

**Comment by AFreeBaldy** [comment]
it seems pretty insignificant i dont know if it will be approved but i can do so i guess

**Comment by ra3orblade** [comment]
https://github.com/anyproto/anytype-ts/pull/816 this PR fixes this behaviour.
