### ISSUE TITLE
Simplified Chinese language 

### ISSUE THREAD

**Issue by gyfuygu** [anyproto/anytype-ts#304]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [ ] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Simplified Chinese language support is not very good, and some places are still in English.
![Snipaste_2023-10-01_09-30-44](https://github.com/anyproto/anytype-ts/assets/125100873/4f7c8a29-6756-4af4-9650-07f54cf56f75)

### Suggested solution

Hopefully, translations will be made where they are still in English

**Comment by fuksman** [comment]
Hello @gyfuygu, localization is a community-driven process. You can contribute to its improvement by suggesting translations through Crowdin: [https://crowdin.com/project/anytype-desktop](https://crowdin.com/project/anytype-desktop).

Please note that pre-installed content, such as object types, relations, and objects from use-cases, is currently not available for localization.
