### ISSUE TITLE
How can i new a "Image" object

### ISSUE THREAD

**Issue by DearZack** [anyproto/anytype-ts#347]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

How can i new a "Image" object

### Suggested solution

How can i new a "Image" object

**Comment by ra3orblade** [comment]
I do not understand this.
