### ISSUE TITLE
Wrap/Unwrap button does not work in Code Snippet Block in New Beta Version

### ISSUE THREAD

**Issue by Xonline-Tech** [anyproto/anytype-ts#350]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

1. Create a new page
2. Create a Code Snippet block
3. Paste part of the single-line text content
4. Click the unwrap button
5. Observation does not take effect

https://github.com/anyproto/anytype-ts/assets/55641276/eaa527a3-37f8-4512-b559-712280bf88a1

### Expected Behavior

unswap effect

### Steps To Reproduce

1. Create a new page
2. Create a Code Snippet block
3. Paste part of the single-line text content
4. Click the unwrap button
5. Observation does not take effect

### Environment

```markdown
- OS: Windows11
- Version: 0.35.20-beta
```

**Comment by ra3orblade** [comment]
https://github.com/anyproto/anytype-ts/commit/774e273561d62c4398d2613511e87d6bcc5bc74e
