### ISSUE TITLE
Anytype can't display it icon in launcher (Linux)

### ISSUE THREAD

**Issue by Anifyuli** [anyproto/anytype-ts#360]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [ ] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Anytype can't show app icon in app launcher using .deb package format.

### Expected Behavior

Anytype can show icon properly without apply some post-install workaroud like copying icon file to it true file location

### Steps To Reproduce

1. Download Anytype `.deb` package format in Anytype official website
2. Install it with APT in command line
3. Installation failed
### Environment

```markdown
- OS:Ubuntu 23.10
- Version:0.35.4
```

### Anything else?

I try to ship Anytype to Pacstall, but I get some error on it
```shell
dpkg: error processing archive /tmp/pacstall/anytype_0.35.4_amd64.deb (--unpack):
 trying to overwrite '/usr/share/icons/hicolor/0x0/apps/anytype.png', which is the diverted version of '/usr/share/icons/hicolor/512x512/apps/anytype.png'
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```
I try to install `.deb` too directly without pacscript I get it too
```shell
dpkg: error processing archive /home/anifyuli/Downloads/anytype_0.35.2_amd64.deb (--unpack):
 trying to overwrite '/usr/share/icons/hicolor/0x0/apps/anytype.png', which is the diverted version of '/usr/share/icons/hicolor/512x512/apps/anytype.png'
Errors were encountered while processing:
 /home/anifyuli/Downloads/anytype_0.35.2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by charlesneimog** [comment]
yes, I had the same problem with making the Arch install. For me, the problem was that the icon of the program is in 0x0 not in other folders like 128x128. Copying the icon to 128x128 and updating the icons with `sudo update-desktop-database` solved the bug for me.

**Comment by Anifyuli** [comment]
> yes, I had the same problem with making the Arch install. For me, the problem was that the icon of the program is in 0x0 not in other folders like 128x128. Copying the icon to 128x128 and updating the icons with `sudo update-desktop-database` solved the bug for me.

Thanks, Bro. I do the same way for `.pacscript` in Pacstall
