### ISSUE TITLE
i need "clear unused images" feature

### ISSUE THREAD

**Issue by DearZack** [anyproto/anytype-ts#361]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

i need "clear unused iamges" feature

### Suggested solution

i need "clear unused iamges" feature

**Comment by ra3orblade** [comment]
This should be moved to Discussions https://github.com/orgs/anyproto/discussions
