### ISSUE TITLE
Add drawing support for anytype

### ISSUE THREAD

**Issue by loepare** [anyproto/anytype-ts#379]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [x] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

I'd love to be able to draw things in anytype, so that I can use it more intuitively as a "notebook" (with a surface i.e.), if I don't wanna type, but rather write with my hand or draw anything.

### Suggested solution

Add support drawing support for anytype (even if only limited to page-objects i.e.)

**Comment by fuksman** [comment]
Hi @loepare, this feature is planned in our [roadmap](https://github.com/orgs/anyproto/projects/1?pane=issue&itemId=29227805).

**Comment by loepare** [comment]
And of course I missed that - my apologies. Thanks for anytype, it's just great!
