### ISSUE TITLE
Missing Anytype icon in Windows 11 taskbar

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [anyproto/anytype-ts#390]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I am using the latest Anytype Beta (0.36.2-alpha-win7) and Anytype in the taskbar appears to not have an icon. Instead, it is replaced with a white page icon with a folded corner. 
![image](https://github.com/anyproto/anytype-ts/assets/152357748/c2c68ef6-9454-461f-a79d-7a95f1ffa90c)
I have not tried to reinstall it yet. The application in the folder and shortcuts to it appear perfectly normal, and the app functions as intended. Just a technical irk.

### Expected Behavior

I expected the app icon in the taskbar to function as normal. one day it stopped working.

### Steps To Reproduce

I do not know what caused this to happen, nor if it replicates on other programs. Here is what I did.
1. Use the anytype beta 0.34.2. This is the one I started with.
2. Upgrade to Anytype Beta (0.36.2-alpha-win7) 
3. May or may not replicate. idk

### Environment

```markdown
- OS: Windows 11
- Version: 0.36.2-alpha-win7
```

**Comment by Atalanttore** [comment]
```
- OS: Linux Mint 21.2 Cinnamon
- Version: anytype_0.36.0_amd64.deb
```

The same problem occurs on Linux Mint. The Anytype icon is neither displayed in the taskbar nor in the Cinnamon menu (start menu).

**Comment by Vortigern-The-Grey** [comment]
This issue for me has since resolved itself thankfully.
