### ISSUE TITLE
Unlink built-in relations with objects

### ISSUE THREAD

**Issue by yhoundz** [anyproto/anytype-ts#410]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [x] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

When I create a custom type and add a built-in relation to it (e.g. tag, description), I cannot unlink them afterwards. This issue does not persist when I add a custom relation of the same type.

Version: 0.36.16-beta

### Suggested solution

Allow users to unlink built-in relations to custom types.

### Additional context

![image](https://github.com/anyproto/anytype-ts/assets/43507714/123fda1d-28d7-4e6c-b4b9-d173dc607b88)
![image](https://github.com/anyproto/anytype-ts/assets/43507714/268a0933-d8b8-4919-bee7-554dd806b834)

**Comment by ra3orblade** [comment]
Already implemented.
