### ISSUE TITLE
Please allow users to decide whether to synchronize content, rather than having to synchronize all content.

### ISSUE THREAD

**Issue by zhouxinghong** [anyproto/anytype-ts#415]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Please allow users to decide whether to synchronize content, rather than having to synchronize all content.

Functional Requirements:

1. Please allow users to decide whether to synchronize content, rather than having to synchronize all content;
2. Please allow users to choose which content needs to be synchronized;

Windows 10
Anytype 0.36

### Suggested solution

Please allow users to decide whether to synchronize content, rather than having to synchronize all content.

Functional Requirements:

1. Please allow users to decide whether to synchronize content, rather than having to synchronize all content;
2. Please allow users to choose which content needs to be synchronized;

Windows 10
Anytype 0.36

**Comment by fuksman** [comment]
Hey @zhouxinghong, with the next release it will be possible to switch client to Local-only mode (no sync to the external infrastructure, only between your local devices).

**Comment by zhouxinghong** [comment]
Hi! Friend, you did a great job 👍. Nowadays, almost every document editor prioritizes local data storage instead of remote server data storage. Because most of the user's work is done locally.

And this mainly involves user data security and privacy issues. As a result, many people who like the tool are afraid to use it.

**Comment by zhouxinghong** [comment]
Hi! friend. Excuse me, is the next version v0.36.22-alpha?

**Comment by fuksman** [comment]
> Hi! friend. Excuse me, is the next version v0.36.22-alpha?

We will release a prod version later today.
