### ISSUE TITLE
About page layout

### ISSUE THREAD

**Issue by chen-jingliang** [anyproto/anytype-ts#420]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

The layout of the ABOUT page 
![SCR-20231223-lzrt](https://github.com/anyproto/anytype-ts/assets/28627641/e8e0a3b7-ee23-4d32-8ae7-44c5cad4d95a)
should also be small and beautiful

### Suggested solution

By default, the left and right margins should be left empty, and no matter how it is stretched, it should have proper margins all around and not stick to the edges.

**Comment by wxrl** [comment]
Agree. The margins are just insanely wide (comparatively) and shall be able to be customized.

**Comment by ra3orblade** [comment]
Fixed
