### ISSUE TITLE
ABOUT page re-optimization

### ISSUE THREAD

**Issue by chen-jingliang** [anyproto/anytype-ts#426]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

The ABOUT page layout issue I reported earlier has been resolved. Thanks to the team for working quickly and efficiently. I opened the page again and realized that the scroll bar on the right side is redundant as it is not used at all and is best displayed directly as a page.
![01](https://github.com/anyproto/anytype-ts/assets/28627641/1042dce9-5579-4695-8b9c-7b803d57cbfa)
![02](https://github.com/anyproto/anytype-ts/assets/28627641/40ca7557-ad25-4e97-a8e6-97e8f194def9)

### Suggested solution

Displaying it directly as a page is best.

**Comment by LavaCxx** [comment]
This problem did not exist in version 0.36.0, but appeared in version 0.37.3.
But it just a easy box model problem, fix it in [this line](https://github.com/anyproto/anytype-ts/blob/54a2860a15cb3e72f7018ec21e6ac85b77585847/electron/about/about.css#L9C41-L9C41)
（没想到anytype中文用户还挺多）
