### ISSUE TITLE
Embed bilibili video

### ISSUE THREAD

**Issue by LavaCxx** [anyproto/anytype-ts#441]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

I hope anytype supports embedding Bilibili videos.

### Suggested solution

I have already written a [demo code](https://github.com/LavaCxx/anytype-ts/tree/embed-bilibili), but lack further support to improve it. Including svg icons, display on other platforms, and parsing bilibili's short links.

### Additional context

<img width="791" alt="image" src="https://github.com/anyproto/anytype-ts/assets/48022591/e5d0af2f-029c-482d-81af-094a38310a12">

**Comment by ra3orblade** [comment]
Please check out this branch, it has a lot of updates and refactoring to embed blocks and iframe code, if you make PR based on that branch we will have less conflicts to resolve. 

We can add icons later, @fuksman

**Comment by ra3orblade** [comment]
Update: merged to main.
