### ISSUE TITLE
PC widgets cannot expand documents containing inline collections according to tree view

### ISSUE THREAD

**Issue by muhanstudio** [anyproto/anytype-ts#442]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

PC widgets cannot expand page containing inline collections according to tree viewHowever, the mobile terminal can be deployed normally.
![Screenshot_2024-01-01-18-40-34-601-edit_io anytyp](https://github.com/anyproto/anytype-ts/assets/29907393/9929c0e1-7700-46d5-85cd-53b1915a6e1c)
![image](https://github.com/anyproto/anytype-ts/assets/29907393/edd60892-d761-4f8c-8068-3bc93ffe0338)

### Expected Behavior

It is hoped that both PC and mobile terminals can expand the tree diagram containing inline collection page normally

### Steps To Reproduce

Create a page A, create an inline set B in the document, the set contains other page NNN, and then fix A to the pendant, you can find that the mobile side can expand the pendant tree, but the PC side cannot

### Environment

```markdown
- OS:Win10
- Version:0.37.3
```

### Anything else?

none

**Comment by ra3orblade** [comment]
Fixed.
