### ISSUE TITLE
Use English names as block menu aliases

### ISSUE THREAD

**Issue by LavaCxx** [anyproto/anytype-ts#451]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

For non-latin language system users especially East Asian users, we often use input methods to output our national characters. However, the current menu invocation in Anytype is based on the interface language, this is not convenient for input method users.

For example, input a **bulleted list**
1. switch to English input
2. hit `/`
3. switch to Chinese input
4. hit `bianhao` to get `编号`(Inputting phrases is always more accurate than inputting a single character.)
5. hit `enter`

As for English, you only need to directly input `bullet` or `bu`.

### Suggested solution

An excellent reference comes from wolai, which integrates English, Chinese characters and pinyin.

![image](https://github.com/anyproto/anytype-ts/assets/48022591/11de7e5b-cd32-416b-aad2-c7e7dca50fbb)
![image](https://github.com/anyproto/anytype-ts/assets/48022591/09e9599b-abb4-48a5-a5e6-5a373be6a007)
![image](https://github.com/anyproto/anytype-ts/assets/48022591/e4f87897-b962-47c4-8e98-e8376464b615)

**Comment by ra3orblade** [comment]
I've actually added this to UtilMenu.blockMapper, it adds english name and description to aliases and translate now has second argument which forces the lang, but we can leave it as it is, does not matter.

`if (commonStore.interfaceLang != Constant.default.interfaceLang) {
				it.aliases.push(translate(nameKey, Constant.default.interfaceLang));
				it.aliases.push(translate(descriptionKey, Constant.default.interfaceLang));
				it.aliases = UtilCommon.arrayUnique(it.aliases);
			};`
