### ISSUE TITLE
'Small' Cards Change Size

### ISSUE THREAD

**Issue by Docfips** [anyproto/anytype-ts#455]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Issue:
On my 'Homepage', I have several items listed in Card View and Small for the pages I go to most.

When I either push the 'enter' key or 'backspace' from empty rows, the preview changes and get's bigger. It only changes after I go to a new page then go back.

### Expectation:
For the 'card' view to *not* change. 

### Reproduction:
1. Have two 'Card Style' previews, size small, next to each other.
2. Either at the top text click enter, or in an empty space, click the backspace button.
3. Change to a different page, then back to 'homepage' to see the correct preview.

### Environment

```markdown
- OS: Windows 11
- Version: 0.37.3
```

### Video
Video showing issue is here: https://youtu.be/5BNSLbkI3Gg

**Comment by ra3orblade** [comment]
Fixed
