### ISSUE TITLE
Mouse selection frame cannot penetrate embedded objects

### ISSUE THREAD

**Issue by LavaCxx** [anyproto/anytype-ts#456]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

![screenshot](https://github.com/anyproto/anytype-ts/assets/48022591/ad632ea1-6a38-4e49-861b-42e6e7a316c1)

### Expected Behavior

![after](https://github.com/anyproto/anytype-ts/assets/48022591/512e0629-8e05-47c1-8a82-9444d045a4a1)

### Steps To Reproduce

None

### Environment

```markdown
- OS: macOS Sonoma 14.2.1
- Version: 0.37.3
```

**Comment by ra3orblade** [comment]
https://github.com/anyproto/anytype-ts/commit/e777ec1769d2f7b8f0ecafdf37df9f58d0d0c21f
