### ISSUE TITLE
Add rounded corners to images and code blocks

### ISSUE THREAD

**Issue by NextPr0gram** [anyproto/anytype-ts#458]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Add rounded corners to images and code blocks

### Suggested solution

Add rounded corners to images and code blocks

**Comment by ra3orblade** [comment]
This was passed to the design team.

**Comment by yasyuk** [comment]
User's images should not have round corners, as it is incorrect to make such changes to user's content.

On Code and other blocks in the editor, I totally agree that they should look consistent. I've set myself the task of reviewing them and adding the same round corners and other rules. Thanks!

**Comment by ra3orblade** [comment]
Closing as it is done.
