### ISSUE TITLE
Dim the background when viewing an image in maximized mode.

### ISSUE THREAD

**Issue by prashantrahul141** [anyproto/anytype-ts#459]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

When viewing an image in maximized mode ( by clicking on it ), the background, in my opinion, should get dimmer. It already happens when opening the profile page ( by clicking on your space name in the top of the side bar ). It is harder to differentiate between the background and the image when there is not enough contrast between them. 

### Suggested solution

Dimming the background similar to when opening the profile page should be enough.

### Additional context

Example: 
Here I'm viewing the image in maximized view, but it's hard to differentiate between the image and the background.
![image](https://github.com/anyproto/anytype-ts/assets/59825803/1c5f8b35-d85c-4d97-9c67-b227d7050d5a)

**Comment by ra3orblade** [comment]
Issue was passed to the design team.

**Comment by ra3orblade** [comment]
Done.
