### ISSUE TITLE
Horizontal lines inside code block

### ISSUE THREAD

**Issue by rzelnik** [anyproto/anytype-ts#462]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When I type three hyphens in a first line of a code snippet, it creates a horizontal line above the code snippet.

### Expected Behavior

Inside code snippets, all typing shortcuts (like for example three hyphens for horizontal line) should be inactive, even in the first line, since we want to be able to type any combination of characters without triggering actions or creation of objects. For example three hyphens are used to divide front matter from the rest of the document.

### Steps To Reproduce

1. Create a code snippet by typing /code
2. Type "---" in the first line of the code snippet
3. The three hyphens will disappear and a new horizontal line will appear above the code snippet

### Environment

```markdown
- OS: Ubuntu 23.10
- Version: 0.37.3
```

**Comment by LavaCxx** [comment]
They prevented this behavior in the table but forgot to do so in the code block as well.
