### ISSUE TITLE
Annoying interactions on page block.

### ISSUE THREAD

**Issue by LavaCxx** [anyproto/anytype-ts#470]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Currently, there are several annoying aspects in terms of UI/UX for page blocks.

1. It is difficult to distinguish page blocks from regular text at a glance.
![image](https://github.com/anyproto/anytype-ts/assets/48022591/93cd95e1-6b78-4596-977f-02da767cc54b)

2. Selection operations cannot be started from page blocks, because it has already entered the page in the instant of clicking(onMouseDown event)
3. The clickable area of page blocks is larger than imagined, combined with the second point, the experience is terribly bad.
![after](https://github.com/anyproto/anytype-ts/assets/48022591/bbafa586-5fbd-4fa8-b9cd-262358afea0b)

### Suggested solution

The first point I don't have a better method either, maybe underlining by default or giving the block a background color when hovering? In any case, you all decide.

About the last two points, I will propose a relevant pr.

**Comment by ra3orblade** [comment]
Can we close this issue since the PR is merged?
