### ISSUE TITLE
The path where the data is saved and the path where the software is installed, as well as synchronization issues.

### ISSUE THREAD

**Issue by mieyeaa** [anyproto/anytype-ts#475]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

The data can be saved in a folder on any hard disk of the computer, not in the C drive.

The software installation is expected to be installed on a portable hard drive.

Data synchronization can be turned off.

### Suggested solution

Software Installation: Provide the installation path during installation.

Data saving: I want a custom storage path.

Data Sync Cloud: Want to provide a On/Off button.

**Comment by fuksman** [comment]
Hi @mieyeaa,
1. Custom storage location is in our roadmap
2. You can change network mode to local-only to disable sync with external infrastructure https://doc.anytype.io/anytype-docs/data-and-security/self-hosting#local-only-mode

**Comment by ra3orblade** [comment]
You can also specify user data directory by adding a flag to launch command `--user-data-dir="D:\Anytype"`

**Comment by mieyeaa** [comment]
> 您还可以通过向启动命令添加标志来指定用户数据目录`--user-data-dir="D:\Anytype"`
Can you use visual graphical operations instead of command line operations? It is the operation of selecting by clicking the mouse.

**Comment by mieyeaa** [comment]
> 嗨，
> 
> 1. 自定义存储位置在我们的路线图中
> 2. 您可以将网络模式更改为仅本地模式，以禁用与外部基础结构 https://doc.anytype.io/anytype-docs/data-and-security/self-hosting#local-only-mode 同步

But I don't want that! I would like to ask you to come up with a graphical switch button that turns on when you need to upload and turns off when you don't want to upload.

**Comment by qwqawawow** [comment]
> Hi @mieyeaa,
> 
> 1. Custom storage location is in our roadmap
> 2. You can change network mode to local-only to disable sync with external infrastructure https://doc.anytype.io/anytype-docs/data-and-security/self-hosting#local-only-mode

The default installation on windows is C:\Users\UserName\AppData\Local\Programs\anytype
I dont know any js,maybe enable allowToChangeInstallationDirectory in package.json?

**Comment by catasystems** [comment]
I want a custom storage path in Android.
