### ISSUE TITLE
The content of latex overflows the boundary.

### ISSUE THREAD

**Issue by LavaCxx** [anyproto/anytype-ts#489]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

![image](https://github.com/anyproto/anytype-ts/assets/48022591/63afdbea-1dc4-4a16-92a4-54a593bd4a0b)

### Expected Behavior

Perhaps recursively find the node with the smallest x value under the first `.base`, and assign the difference as `margin-left` to `.base`
![image](https://github.com/anyproto/anytype-ts/assets/48022591/849cd446-6f76-4d7a-b063-b25bbb59e8d9)

### Steps To Reproduce

None

### Environment

```markdown
- OS: macOS Sonoma 14.2.1
- Version: 0.37.3
```

**Comment by ra3orblade** [comment]
Not a good idea to find something recursively, if there will be hundred of blocks it will become slow.

**Comment by ra3orblade** [comment]
https://katex.org/docs/options.html
you can try this: `fleqn: boolean. If true, display math renders flush left with a 2em left margin, like \documentclass[fleqn] in LaTeX with the amsmath package.`
