### ISSUE TITLE
SketchFab Embed

### ISSUE THREAD

**Issue by spacecoder7** [anyproto/anytype-ts#492]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Sketch fab is a website of 3D models and has some free models that can be embedded into Anytype

https://sketchfab.com/categories

### Suggested solution

Add Sketchfab to embed options

**Comment by ra3orblade** [comment]
Added to internal tracker.

**Comment by LavaCxx** [comment]
> Added to internal tracker.

I will take a look later

**Comment by fuksman** [comment]
Closed in #496
