### ISSUE TITLE
The input area within the embedded block should prevent selection events

### ISSUE THREAD

**Issue by LavaCxx** [anyproto/anytype-ts#494]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

It is easy to affect the entire block when editing the contents here
![demo](https://github.com/anyproto/anytype-ts/assets/48022591/9308a8c8-0a89-4764-a415-4ab3543648f0)

### Expected Behavior

None

### Steps To Reproduce

None

### Environment

```markdown
- OS: macOS 14
- Version: 0.37.3
```

### Anything else?

Perhaps I will take a look at it along the way when I finish resolving the embedding

**Comment by ra3orblade** [comment]
https://github.com/anyproto/anytype-ts/commit/f898bf3ed743e4183dd67b4ec23a85b3f2a1bf3b
