### ISSUE TITLE
mermaid.js causes document to "jump" to the beginning on every diagram update

### ISSUE THREAD

**Issue by xfactor2000** [anyproto/anytype-ts#507]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

After embedding a large mermaid.js diagram, like this mindmap:
https://mermaid.js.org/syntax/mindmap.html,

I experience "jumps" to the beginning of the document each time I edit the diagram code. This makes working with the diagram annoying, as I need to scroll back to the code after each change. Also, the diagram is rendered incorrectly after the code is changed, so I need to click outside of text area to make the block re-render, and then edit the code again.

### Expected Behavior

A diagram would correctly update while in editing mode and without scrolling the document all the way up each time the code is changed.

### Steps To Reproduce

1. Create a note
2. Embed mermaid.js block in it
3. Paste the code from this link: https://mermaid.js.org/syntax/mindmap.html
4. Try to change the code of the diagram. The document will jump up, and the diagram will be rendered incorrectly until you click outside the code window to make it lose focus.

### Environment

```markdown
- OS:EndeavorOS Galileo
- Version: Rolling release
```

### Anything else?

![image](https://github.com/anyproto/anytype-ts/assets/4991585/5c1ef34b-4b8e-424d-892a-ca797306578b)

This is how the diagram looks right after changing the code. Note the code window is not seen after the document jumped up. It's still in editing mode, however, and once you click outside of code window, the image is re-rendered correctly.

**Comment by ra3orblade** [comment]
This is fixed in latest beta.
