### ISSUE TITLE
Support for inserting images that already exist in Space

### ISSUE THREAD

**Issue by syfxlin** [anyproto/anytype-ts#508]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Anytype can insert an image into Space by Picture menu and display the image content. However, sometimes we may refer to an existing image in Space, but currently the Picture menu does not allow us to select an image that already exists in Space, and if we insert an image by Add link, the image content will not be displayed.

<img width="754" alt="image" src="https://github.com/anyproto/anytype-ts/assets/28844480/64187189-0c4c-44f1-a6d3-a4c955d28ff7">

### Suggested solution

Please provide a function in the Picture menu to select an image that already exists in Space.

### Alternative

Displaying the image content of an image inserted using the Add link.

### Additional context

The same problem occurs with other types of attachments, such as File or PDF.

**Comment by jberstler** [comment]
+1 for this.

I think the right UX here might be something like this:
![slice1](https://github.com/anyproto/anytype-ts/assets/7012682/d236bf5e-5364-46a2-87b1-bc8257641b63)

Clicking the "Select an existing picture" link could bring up the standard search modal (though pre-filtered to picture objects). Even better would be if the filtered images showed as a small 2-column grid in the search modal:
![search modal](https://github.com/anyproto/anytype-ts/assets/7012682/3c8861f2-8818-4b03-a0fa-67df067e5d5e)

You could also consider instead using the existing `/picture` UX and requiring the user to paste the link obtained by opening the existing picture object and copying its link, but this is more tedious than using the search modal.

**Comment by syfxlin** [comment]
I found that this issue has been improved in version 0.41.1, so close this issue.

![image](https://github.com/anyproto/anytype-ts/assets/28844480/9e4e6041-c0bc-4668-9e6f-0e71fcab450e)

**Comment by pjarnfelt** [comment]
This feature shouldn't be hidden behind a right click context menu. That's bad UX. I had to find this thread to find the feature and new comers might have the same experience.
