### ISSUE TITLE
Barely readable text on mermaid.js diagrams in dark mode

### ISSUE THREAD

**Issue by xfactor2000** [anyproto/anytype-ts#518]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The text on mermaid.js diagrams is not well readable when using dark mode.

### Expected Behavior

The text should be readable

### Steps To Reproduce

1. Create a note
2. Embed a mermaid diagram
3. The text on the links is dark-grey on black.

### Environment

```markdown
- OS: EndeavourOS
- Version: linux x64 6.7.1-arch1-1
```

### Anything else?

![image](https://github.com/anyproto/anytype-ts/assets/4991585/f9b2a6fe-66e7-42fd-a805-35afeab3b42d)

**Comment by xfactor2000** [comment]
@ra3orblade must say I'm really impressed by the progress. Keep it up. The app is awesome.

**Comment by ra3orblade** [comment]
Thank you
