### ISSUE TITLE
Quick capture shortcut not working? 

### ISSUE THREAD

**Issue by sjmgarnier** [anyproto/anytype-ts#526]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The shortcut help page lists "CTRL+ALT+N" as the shortcut to trigger the quick capture menu. This shortcut doesn't seem to work on my install. All other shortcuts that I've tried so far work as expected. The quick capture menu works as well when I right-click on the "+" icon. 

### Expected Behavior

The shortcut should open the quick capture menu. 

### Steps To Reproduce

From any page, hit "CTRL+ALT+N". Nothing happens. 

### Environment

```markdown
- OS: macOS 14.2.1
- Version: 0.38.0
```

**Comment by ra3orblade** [comment]
It's Cmd/Ctrl now, fixed in shortcut list.

**Comment by sjmgarnier** [comment]
@ra3orblade You mean "Cmd+Alt+N"? If yes, this doesn't work either on my machine at least.

**Comment by ra3orblade** [comment]
Sorry, I've double checked and it was not working indeed since Cmd + Alt + N is a special code `^` called `dead`, lol =) I've fixed it.

**Comment by sjmgarnier** [comment]
Great, thanks.
