### ISSUE TITLE
App size is unexpectedly large

### ISSUE THREAD

**Issue by pontaoski** [anyproto/anytype-ts#537]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The app is about 300MB compressed and 600MB uncompressed, which is rather exorbitant for an app that boils down to notetaking with hyperlinks.

### Expected Behavior

The app is more in line with other app sizes, or at least is reduced.

### Steps To Reproduce

Download the app

### Environment

```markdown
All Environments
```

**Comment by pontaoski** [comment]
Low-hanging fruits (that make up about 50% of the app size):
- the changelogs have very high-resolution high-fps videos which comprise about 200MB of the app's uncompressed size. this is overkill and the videos could be reduced in resolution, fps, and bitrate to compensate.
- the binary `anytypeHelper` seems to be built with debug symbols and other information that should probably be stripped in release builds (it looks like a Go binary, therefore `-ldflags "-w -s"` may be of use

Medium-hanging fruits:
- Changelogs' media assets could be distributed on-demand rather than always being bundled with the app, since a user is not likely to consult them more than once, while the on-disk space will always be incurred

High-hanging fruits (the other 50% of the app size):
- Electron requires shipping an entire browser engine with the app. Most systems ship with a web view, so unless there's specific integration with the Chromium engine required, the OS-provided ones can be used instead to the same/similar effect. [Tauri](https://tauri.app/), [Webview](https://github.com/webview/webview_go), and [Lorca](https://github.com/webview/webview_go) are ready-made solutions to call into the OS's web view and to bind between it and the outside world.

**Comment by ra3orblade** [comment]
I've removed videos and other release notes materials to CDN, so now app size is 100MB lower, we will discuss with middleware team reducing binary size and moving from Electron is a bit too much, we use a lot of functionality of Electron and moving away from it will take significant amount of time.

**Comment by curlykay** [comment]
I totally agree that the team continues to use electron builds, it allows for more efficient feature development and avoids spending a lot of time and effort on dealing with webview compatibility issues.
But comparing the installer size of similar apps, Appflowy: 51MB, Craft: 88MB, Affine:167MB. anytype's 300+MB is indeed unexpectedly large.

**Comment by ra3orblade** [comment]
> I totally agree that the team continues to use electron builds, it allows for more efficient feature development and avoids spending a lot of time and effort on dealing with webview compatibility issues. But comparing the installer size of similar apps, Appflowy: 51MB, Craft: 88MB, Affine:167MB. anytype's 300+MB is indeed unexpectedly large.

its now 165 on Windows, and we have a principle of offline-first approach and this practically means that if we use for example emojis as pictures than these pictures should be bundled with the app, and there is 50Mb of them. So I can optimise the build but there is a limit to that. And as said earlier Electron itself adds 300Mb.

**Comment by ra3orblade** [comment]
Closing for now, reducing middleware size should be created as a different issue within [anytype-heart](https://github.com/anyproto/anytype-heart) repository.
