### ISSUE TITLE
Poor performance on Hyprland with Nvidia

### ISSUE THREAD

**Issue by AdyanshMishra** [anyproto/anytype-ts#572]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [ ] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

The AUR package of anytype runs extremely poorly on using it on Hyprland with a Nvidia graphics card. The app is completely unusable and trying to run it without hardware acceleration(which is the issue on most other applications) with the --disable-gpu flag does not help at all.

### Expected Behavior

The app should have run smoothly with little to no flickering as is the case on all X-org WMs. Even with the quirks of Hyprland with nvidia, it should have been at the point of usability.

### Steps To Reproduce

1. Do a minimal arch install.
2. Setup hyprland with nvidia and use dkms drivers as per the hyprland wiki.
3. Download anytype-bin from aur.

### Environment

```markdown
- OS: Arch Linux  
- Version: 2024.02.01
```

### Anything else?

https://github.com/anyproto/anytype-ts/assets/158471433/bc2de38b-5cb7-4866-99a7-2d35b9b24299

**Comment by IronRevelation** [comment]
@AdyanshMishra I had the same problem, it's because it is running under xwayland. Try adding The following flags:
 --enable-features=UseOzonePlatform --ozone-platform=wayland
 to the .desktop file that opens anytype. If you need any more information feel free to ask

**Comment by AdyanshMishra** [comment]
@IronRevelation Thank-you for you help, the performance is much better now.
