### ISSUE TITLE
Card preview layout acting weird

### ISSUE THREAD

**Issue by ravnida** [anyproto/anytype-ts#579]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Card preview layout renders as horizontal tiles under certain conditions of zoom and ordering as seen in the video

### Expected Behavior

They should render as little vertical cards as usual

### Steps To Reproduce

It's easier to check the video rather than explaining it :)

### Environment

```markdown
- OS: macOS 14.3.1
- Version: 0.38.0
- M2 Pro 14"
```

### Anything else?

https://github.com/anyproto/anytype-ts/assets/156254153/c6543c46-e1fb-4c80-b752-1a151ae64852

**Comment by ra3orblade** [comment]
Fixed, check latest version.

**Comment by ravnida** [comment]
yep, perfectly fine!
