### ISSUE TITLE
Import anytype from Obsidian?

### ISSUE THREAD

**Issue by csdjk** [anyproto/anytype-ts#609]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Import anytype in batches from Obsidian. Because there are too many md files, it takes a lot of time to import a single one

### Suggested solution

Import anytype in batches from Obsidian. and Associate each note by folder name

**Comment by fuksman** [comment]
Hello @csdjk, this feature request already exists. 
https://community.anytype.io/t/import-from-obsidian-md/2359/18

**Comment by csdjk** [comment]
> Hello @csdjk, this feature request already exists. https://community.anytype.io/t/import-from-obsidian-md/2359/

Only a single markdown file can be imported. If the Obsidian workspace is packaged into a .zip file for import, each imported file will not have the correct title.
