### ISSUE TITLE
Javascript error: win is not defined

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [anyproto/anytype-ts#618]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When attempting to quit, check for updates or open anytype from the system tray, I experienced this error:
![image](https://github.com/anyproto/anytype-ts/assets/152357748/05691ce1-1521-4660-b966-5cd208aa4118)
I cannot close anytype, except from the task manager.

### Expected Behavior

I expected to be able to quit, open anytype and check for updates from the system bar, as I always have.

### Steps To Reproduce

1. Download the latest Alpha release 0.39.7 for Windows 11
2. Close the window and attempt to re-open, check for updates or quit from the system tray

### Environment

```markdown
- OS: Windows 11
- Version: Anytype Alpha v0.39.7-alpha
```

**Comment by ra3orblade** [comment]
Sorry, was fixing a bug and created a new one, now fixed https://github.com/anyproto/anytype-ts/commit/c0869c98dc935f600dd18fa16a4c2f24dd6b29ef
