### ISSUE TITLE
Can not mount AppImage

### ISSUE THREAD

**Issue by MyShlongIsLongAT** [anyproto/anytype-ts#623]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I did update my desktop environment from plasma5 to plasma6.

After installing the new update, I checked my AUR packages and updated the rest of my system - including anytype-bin from version 0.38.<...> to 0.39.0.1.

When starting anytype via konsole following error appears.

![image](https://github.com/anyproto/anytype-ts/assets/72039636/2de711e5-9d06-4f4a-992e-6afb6c59c61a)

### Expected Behavior

It should open the anytype app, like before.

### Steps To Reproduce

1. use Arch Linux with kernel version 6.8.1-zen1-1-zen
2. use plasma6
3. install the anytype-bin AUR package via yay
4. start anytype in the konsole

### Environment

```markdown
- OS: Arch Linux
- Kernel: 6.8.1-zen1-1-zen
- Desktop Environment: plasma6
```

### Anything else?

Somehow, running the AppImage provided by your site, Anytype works as expected.

Anytype 0.39.0.1 works like a charm on my colleague's system.

**Comment by ra3orblade** [comment]
Anytype AUR package is maintained via community user, ask in Telegram group please.

**Comment by ra3orblade** [comment]
Closing, if you have any further questions please create a post on https://community.anytype.io/.
