### ISSUE TITLE
Misaligned gridlines in calendar view

### ISSUE THREAD

**Issue by chen-jingliang** [anyproto/anytype-ts#624]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When switching to calendar view, the topmost grid line appears misaligned if there is a scrollbar on the right, or normal if there is no scrollbar on the right. Another problem is that the bottom most border line appears to be separated from the top grid, which is a strange phenomenon.

### Expected Behavior

The gridlines are not out of place.

### Steps To Reproduce

As soon as the window is resized in the calendar view, the error appears.

### Environment

```markdown
- OS:MAC OS 14.4
- Version:0.39.10
```

### Anything else?

<img width="1183" alt="01" src="https://github.com/anyproto/anytype-ts/assets/28627641/afdb3c02-2a88-4197-bc8d-ee73d2956615">
<img width="1178" alt="02" src="https://github.com/anyproto/anytype-ts/assets/28627641/d2cab7fe-4856-428a-a927-b137987126fa">
<img width="1190" alt="03" src="https://github.com/anyproto/anytype-ts/assets/28627641/a659f7ab-2fc6-4733-9060-af7075a4860a">

**Comment by ra3orblade** [comment]
Fixed with https://github.com/anyproto/anytype-ts/commit/f10e08db806577b745e66cc001b6d38d763cfb92
