### ISSUE TITLE
Anytype (0.39.10) does not reopen window once closed on Linux (GNOME).

### ISSUE THREAD

**Issue by adhadse** [anyproto/anytype-ts#630]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I'm using Anytype (0.39.10-alpha) RPM package on Fedora 39, GNOME. On first startup the application starts completely fine but once I close it (clicking the close button), subsequently the window does not open or is not presented. 

The issue was persistant with 0.39.0 as well and so I tried if newer version are also having the same issue. I looked on Anytype forum but didn't find anything specific to Linux or current Anytype version. 

I have to terminate `anytype` and `AnytypeHelper` from system monitor and relaunch it. 

After I terminate it I get these log file of crash (may or may not be related to the above issue)
```
{"level":"ERROR","ts":"2024-03-25T10:29:23.942+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}
{"level":"ERROR","ts":"2024-03-25T10:29:23.942+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}
{"level":"ERROR","ts":"2024-03-25T10:29:23.942+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}
{"level":"ERROR","ts":"2024-03-25T10:29:23.942+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}
{"level":"ERROR","ts":"2024-03-25T10:29:23.942+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}
{"level":"ERROR","ts":"2024-03-25T10:29:23.942+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}

{"level":"ERROR","ts":"2024-03-25T10:29:23.943+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}
{"level":"ERROR","ts":"2024-03-25T10:29:23.943+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}
{"level":"ERROR","ts":"2024-03-25T10:29:23.943+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}
{"level":"ERROR","ts":"2024-03-25T10:29:23.943+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}

{"level":"ERROR","ts":"2024-03-25T10:29:23.943+0530","logger":"fileobject","msg":"index loop: apply to smart block: build tree: peer id not found in context"}

{"level":"INFO","ts":"2024-03-25T10:29:25.388+0530","logger":"common.commonspace.headsync","msg":"sync done:","spaceId":"bafyreiaqcqnshvu4kynultrp2ggbwnwe3gekwyx52xh5op5y34t7zlgn5u.6fao1qw23v00","newIds":0,"changedIds":0,"removedIds":0,"already deleted ids":0,"peerId":"12D3KooWD27VZCngpb5QeGyHJFUCDoQpgePTbvnmEsZYZxknmrpK"}

{"level":"ERROR","ts":"2024-03-25T10:29:53.563+0530","logger":"anytype-mw-api","msg":"stream eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWVkIjoiZUhuY3pwVk4ifQ.fW9GjXHPJjOZJ3ivEm00h0xYjZIqvZAYIFGo4XthYlg context canceled"}
```

### Expected Behavior

The subsequent window should be presented since the application is not closed, just the window is closed.

### Steps To Reproduce

1. Install Anytype `0.39.10-alpha` on Linux (preferably Fedora)
2. Start the application
3. Close the window
4. Try opening the window from dash.

### Environment

```markdown
- OS:Fedora 39 Workstation
- Version:0.39.10-alpha / 0.39.0
```

**Comment by vohefwdskcmigw** [comment]
Doesn't anytype show as a background application on your dock? So a temporary solution would be clicking on background application icon on your dock. 

But I still think it's an issue that AnyType's window doesn't pop up when the application is launched in the background.

**Comment by adhadseKavida** [comment]
> Doesn't anytype show as a background application on your dock? So a temporary solution would be clicking on background application icon on your dock.
> 
> But I still think it's an issue that AnyType's window doesn't pop up when the application is launched in the background.

No, it doesn't. GNOME doesn't work with docks it works with 'Dash', it's extensions which make it look and behave like dock. But neither shows it as background. 

On GNOME, we have this 'Background Apps' section in Quick Settings, but Anytype doesn't show up there (just a pick from internet, Anytype isn't shown as background application yet):
![image](https://github.com/anyproto/anytype-ts/assets/126055159/568c022b-e407-4ea0-a381-745444e77473)

**Comment by filip-anytype** [comment]
@adhadseKavida If I remember correctly, the background apps section of Gnome only shows flatpak apps for now, so Anytype wouldn't show there. You'll need some kind of tray icons extensions for Anytype to show there (for instance, [Tray Icons Reloaded](https://extensions.gnome.org/extension/2890/tray-icons-reloaded/)).

**Comment by ra3orblade** [comment]
Fixed in latest alpha.

**Comment by ra3orblade** [comment]
Closing, no replies.
