### ISSUE TITLE
Can you actually ask the user where Anytype should be installed? It takes up too much space on C:

### ISSUE THREAD

**Issue by Welding-Torch** [anyproto/anytype-ts#664]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Hi. Can you be more considerate of users like me who are running low on storage on C: and don't want an app that just installs itself (with no conformation) to C:/Users/<USERNAME>/AppData/Roaming/Anytype ?

### Suggested solution

I'd really appreciate it if you added a dialogue asking users where they want to install Anytype i.e. in which folder. 

### Additional context

If you don't know how to add this, use Inno Setup.

**Comment by fuksman** [comment]
Hi, ability to choose custom storage location will be released soon

**Comment by Welding-Torch** [comment]
Great to hear, thank you
