### ISSUE TITLE
When will excalidraw arrive?

### ISSUE THREAD

**Issue by soucosmo** [anyproto/anytype-ts#665]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Looking at the activities in the repository, I saw that some commits already suggest integration with excalidraw, is there a plan for this functionality? Any estimated date?

### Suggested solution

Excalidraw

**Comment by ra3orblade** [comment]
I could not do it without react@17 and it takes a lot of effort to upgrade, so there are plans but I can't give any estimates unfortunately.

**Comment by ra3orblade** [comment]
Closing as duplicate of https://github.com/anyproto/anytype-ts/issues/548
