### ISSUE TITLE
Mermaid breaks in anything case

### ISSUE THREAD

**Issue by Neirth** [anyproto/anytype-ts#666]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Exploring anytype I see that any kind of mermaid chart breaks:

This is the example:
![image](https://github.com/anyproto/anytype-ts/assets/7413024/4bd90eda-9918-4e25-af69-4f19d47ca551)

### Expected Behavior

Can render the mermaid chart normally

### Steps To Reproduce

1. New Page,
2. New Mermaid Block
3. Paste the [Mermaid example](https://mermaid.js.org/syntax/flowchart.html#a-node-default):
```
---
title: Node
---
flowchart LR
    id
```
3. Show how this breaks

### Environment

```markdown
Versión del sistema operativo: win32 x64 10.0.19045
Versión de la app: 0.39.0
Número de compilación: build on 2024-03-05 15:37:42 +0000 UTC at #a7986fffadcc2031b1eb3372265db5dda05f4c6d (dirty)
Versión de la librería: v0.32.1
Identidad Anytype: 
ID de Analíticas: dc62ecf5-2aeb-4bcb-926b-f91c538148e7
ID del dispositivo: 12D3KooWFKs3pcsMAkiT3JdQgajUdmcBPWheWfHmUBe5z9G6iiCF
```

**Comment by ra3orblade** [comment]
<img width="817" alt="Screenshot 2024-04-14 at 18 54 58" src="https://github.com/anyproto/anytype-ts/assets/1450818/d5fb803e-cc7c-4d6a-80e0-02d9172b7ff3">
works for me

**Comment by langtind** [comment]
This works for me as well. However, I am using the latest beta version, which includes Mermaid 10.9.0.

**Comment by Neirth** [comment]
@langtind, in the production version breaks, but in the beta version I see that works correctly. I propose to wait for the release before close the issue for avoid regressions.

**Comment by ra3orblade** [comment]
I have updated the version recently, maybe it uses some new functionality.
