### ISSUE TITLE
Is it possible to install and update anytype  through scoop or homebrew?

### ISSUE THREAD

**Issue by yxdxx** [anyproto/anytype-ts#682]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Is it possible to install and update anytype  through scoop or homebrew? 
or it is in plan?

### Suggested solution

people can just run "scoop install anytype"  to install it, and update it by "scoop update"?   

### Alternative

as above.

**Comment by ra3orblade** [comment]
There is a formula for Homebrew for Anytype https://formulae.brew.sh/cask/anytype, but it's not maintained by developers and there is no Scoop app. There are no plans for these package managers unless it will be contributed by community.

**Comment by ra3orblade** [comment]
Closing as there are no plans for this at the moment.

**Comment by aliesbelik** [comment]
Available in scoop's Extras bucket:

```
scoop bucket add extras
scoop install anytype
```
