### ISSUE TITLE
Links with uncommon URI schemes don't work 

### ISSUE THREAD

**Issue by adriancampos** [anyproto/anytype-ts#696]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Currently, links with a custom uri scheme aren't clickable. For example, a link that points to `vscode://file/project` doesn't show anything on hover or do anything on click. It behaves like regular text.

### Expected Behavior

The link should attempt to open when clicked.

### Steps To Reproduce

1. Create a link with value `vscode://file/project`
2. Click on the link, expect it to open the link
3. Compare with `mailto://path` or other allowed URI schemes

### Environment

```markdown
- OS: Windows 11
- Version: 0.40.8
```

### Anything else?

It seems that specific schemes are explicitly allowed [here](https://github.com/anyproto/anytype-ts/blob/2b39c151479d2808cb0396e25b22547129691483/src/ts/lib/util/common.ts#L889). Is there a reason to not allow everything? If so, could a confirmation box (like the one in Chrome) be implemented for schemes that aren't automatically allowed?

**Comment by ra3orblade** [comment]
Fixed.
