### ISSUE TITLE
Custom themes/css

### ISSUE THREAD

**Issue by ThatOneCalculator** [anyproto/anytype-ts#699]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

There's only a black and white theme, with no way to make the background, foreground, or any other elements have custom styling.

### Suggested solution

The ability to make custom color schemes, or at least load custom CSS, would be great for those of us who like to theme our applications for a consistent desktop environment.

**Comment by ra3orblade** [comment]
https://community.anytype.io/t/tutorial-of-custom-css/14234

**Comment by ThatOneCalculator** [comment]
Ah, thank you. Why  is that not documented?

**Comment by ThatOneCalculator** [comment]
Also, I wonder if there's a speedrun leaderboard for making a theme 😄

https://github.com/rose-pine/anytype

![image](https://github.com/anyproto/anytype-ts/assets/44733677/28302d0e-7996-4491-9f81-7d3eadb55a7c)
![image](https://github.com/anyproto/anytype-ts/assets/44733677/0c1eaa0b-b076-47f0-a5a9-9dc2080a5398)
