### ISSUE TITLE
Multiplayer mode: Anytype does not sync the characters after a / mark the first time I input them from Mac

### ISSUE THREAD

**Issue by deruloop** [anyproto/anytype-ts#705]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

In a shared space, inside a note, I write something with my Mac with a / mark inside. Only the part before the / mark is synced, the rest is ignored. In fact If I switch device only the part before the / mark has been synced and the other device tells me there's nothing else to sync. I've tried with a friend and the synced result is wrong even from another collaborator's device perspective.

The problem seems to be only from Mac, if I input the same text from iPhone even the text after the / mark is synced.

### Expected Behavior

All the contents I have put in input from a device are synced when I see them in the other device or when other collaborators sees it.

### Steps To Reproduce

1. In a shared space, inside a note, I write from Mac for example:
"Test 01/05"
2. Then I go on another device to see the output and after the sync has happened it says:
"Test 01/"

### Environment

```markdown
I've tried to input text from 2 different Mac with the same result:

First Mac test:
- OS: macOS 13.6.3
- Version: 0.40.8

Second Mac test:
- OS: macOS 14.1
- Version: 0.40.8

And also did the same from iPhone:
- OS: iOS 17.4.1
- Version: 0.29.3
```

**Comment by ra3orblade** [comment]
Fixed in main.

**Comment by ra3orblade** [comment]
Closing.
