### ISSUE TITLE
Anytype data is stored in APPDATA on Windows

### ISSUE THREAD

**Issue by Darthagnon** [anyproto/anytype-ts#717]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

As far as I can tell from Anytype >> Settings >> Vault >> Data Management (settings layout is very confusing), Anytype data is stored in `C:\Users\Username\AppData\Roaming\anytype\data` (similar to most other Chromium/Electron software). As Appdata is a hidden folder on Windows and full of a lot of frequently-changing system files, it is likely to be missed in computer backups, unlike visible shell folders like **My Documents**. Thus, Anytype data is ephemeral and can very easily be lost on computer migration, unless either (a) it is manually exported first, or (b) we trust the cloud (I don't). 

Please can you store Anytype data in `My Documents\anytype\data` so it will not be missed in backups, or provide a user-configurable path? 

Could this also be made easier to find, as the current settings layout, splitting all settings between 5 submenu entries in a non-standard dropdown is very confusing? I would suggest a different layout, in a separate issue.

### Expected Behavior

Anytype should store user data in `My Documents\anytype\data` as do most other content-creation programs in the past 30 years, rather than with temporary system settings in the hidden Appdata folder. 

### Steps To Reproduce

1. Install Anytype on Windows
2. It stores its data in a hidden folder usually used for temporary settings and caches. Appdata is likely to be missed in computer backups and data will be lost
3. Current workarounds are either manually export Anytype data, which will not help if computer dies suddenly, or trust the cloud (which is someone else's computer, requires internet, and is not a backup)

### Environment

```markdown
- OS: Windows 10
```

**Comment by ra3orblade** [comment]
You can change the path on the first app screen in the settings: 
<img width="728" alt="Screenshot 2024-05-10 at 15 21 01" src="https://github.com/anyproto/anytype-ts/assets/1450818/0e272f7c-27bb-4618-9328-ed995641368c">

**Comment by Darthagnon** [comment]
Until I get around to opening another issue (issue template is rather time consuming and does not fit), a more standard, compact

> You can change the path on the first app screen in the settings: <img alt="Screenshot 2024-05-10 at 15 21 01" width="728" src="https://private-user-images.githubusercontent.com/1450818/329590752-0e272f7c-27bb-4618-9328-ed995641368c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDc1NzgsIm5iZiI6MTcxNTM0NzI3OCwicGF0aCI6Ii8xNDUwODE4LzMyOTU5MDc1Mi0wZTI3MmY3Yy0yN2JiLTQ2MTgtOTMyOC1lZDk5NTY0MTM2OGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMTMyMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc0NGNlNmIxZTQ5ZGFkOGQ3YjRhYjQ5MmQ4YWUwYTBjMTgxNjRjYzk1YTM4YTcwNDkyOGI5YjMxN2I2NDExNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xs-FAxJY0rmxBo6wQNtwqXtmmEGhN4qahl1h2ortca0">

Where do I find this page? It is not present in:
- `Anytype >> Settings`
- `Anytype >> Settings >> Space`
- `Anytype >> Settings >> Vault >> <Username>`
-  `Anytype >> Settings >> Vault >> Preferences`
- `Anytype >> Settings >> Vault >> Appearance`
- `Anytype >> Settings >> Vault >> Pin Code`
- `Anytype >> Settings >> Vault >> Spaces`
- `Anytype >> Settings >> Vault >> Data Management` 
- `Anytype >> Settings >> Vault >> Key` 
- `Anytype >> Settings >> Vault >> Membership` 

I'm on Anytype v0.40.8

**Comment by filip-anytype** [comment]
@Darthagnon You need to log out first. You then click on a button in the top right corner.

**Comment by Darthagnon** [comment]
> @Darthagnon You need to log out first. You then click on a button in the top right corner.

Aha, I found it. `Anytype >> Settings >> Vault >> Log Out`, then I clicked on the almost invisible cog button in the top right, and it gives the secret settings menu ☺
