### ISSUE TITLE
Anytype leaves orphaned processes running after being closed (Windows)

### ISSUE THREAD

**Issue by Darthagnon** [anyproto/anytype-ts#718]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

If I disable Anytype from showing in the system tray and close it, it leaves 5 processes (250mb RAM) running orphaned in the background. Subsequent attempts to reopen Anytype fail, until I manually kill those processes with Task Manager/Process Hacker.
![chrome_240510_61](https://github.com/anyproto/anytype-ts/assets/20792748/df270294-8636-4f15-a1aa-6ecb70e1e1e7)

### Expected Behavior

If I disable Anytype from showing in the system tray and close it, I expect it to fully close and leave nothing running in the background. 

Recommend renaming option `Anytype >> Settings >> Show Anytype in system tray` to `Anytype >> Settings >> Run Anytype in background` to more accurately reflect the expected and desired behaviour. System tray is for showing processes running in background, and hiding systray icons while still running is a dark pattern or a serious bug.

NB. Settings layout is also confusing.

Related issues: #630

### Steps To Reproduce

1. Run Anytype
2. Goto `Anytype >> Settings >> Show Anytype in system tray` and disable it
3. Close Anytype. There is no icon in systray to show it is still running, or to reopen the program to properly close it.
4. Check in Task Manager/Process Hacker, and find 5 orphan processes still running. Anytype will not reopen until those processes are manually killed.
5. There seems to be no way to properly close Anytype.

### Environment

```markdown
- OS: Windows 10
```

**Comment by ra3orblade** [comment]
Fixed in latest alpha.

**Comment by adhadse** [comment]
The latest alpha seems to crash before even loading the UI, and leaves orphaned process just like this on Linux.

**Comment by ra3orblade** [comment]
Yes, cause latest alpha on the moment of writing the comment was different, the most recent one crashes and I didnt rebuild yet.

**Comment by ra3orblade** [comment]
Closing as it is done.
