### ISSUE TITLE
In the callout component when I try to write this letter (*) it get's deleted.   

### ISSUE THREAD

**Issue by Abderrahmane-Deffaf** [anyproto/anytype-ts#735]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I tried to write this text u ∈ ∑* but I couldn't write the * letter it's getting deleted automatically 

### Expected Behavior

format the word correctly 

### Steps To Reproduce

1. add a callout 
2. try to write the following u ∈ ∑* 

### Environment

```markdown
- OS: Windows
- Version: 11
```

**Comment by ra3orblade** [comment]
I will check.

**Comment by ra3orblade** [comment]
It's not deleted in the current main branch, so it's fixed.

**Comment by Abderrahmane-Deffaf** [comment]
ok thanks

**Comment by ra3orblade** [comment]
Closing as there are no further comments.
