### ISSUE TITLE
First sentence of object is on the title bar while the app is locked

### ISSUE THREAD

**Issue by NoteMyBrain** [anyproto/anytype-ts#747]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When the app is locked by PIN, the beginning of the last opened object, where the lock took place is written on the title bar which can be read by unauthorised users creating a risk of data taken out of hand.

### Expected Behavior

The title bar should only write 'Anytype' when the app is locked.

### Steps To Reproduce

The bug can be reproduced by opening and editing an object, then leaving the app go idle and get locked by PIN.

### Environment

```markdown
- OS: Windows 11
- Version: 0.40.8
```

### Anything else?

![a1](https://github.com/anyproto/anytype-heart/assets/171244508/53c567b2-60c5-4056-94ab-a1f45fda76a8)
![a2](https://github.com/anyproto/anytype-heart/assets/171244508/be1ccefe-be3a-4f54-8fb9-c9d8a7f97a18)

**Comment by ra3orblade** [comment]
This is fixed in current main/latest alpha and beta builds.
