### ISSUE TITLE
Check for update doesn't do anything

### ISSUE THREAD

**Issue by rzelnik** [anyproto/anytype-ts#75]
**Describe the bug**
Clicking to "Check for update" doesn't show any info about new version availability.

**To Reproduce**
1. Go to 'Anytype > Check for updates'
2. Click on 'Check for updates'
3. Nothing happens

**Expected behavior**
I would expect information about new version availability or "your application is up-to-date" message.

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Version: 0.33.3 (manual .deb installation)

**Comment by Biepa** [comment]
Hey @rzelnik,
It shows this for me:
![grafik](https://github.com/anyproto/anytype-ts/assets/25102748/0c038270-16eb-487e-ba9d-6135309d0a9b)

Is it possible you had no connection or are having a setup where the connection to the update server may be blocked?

**Comment by rzelnik** [comment]
The connection is definitely all right. I don't have any blocked ports or whatever. I can trace the triggered action through Dev Tools, Console etc., if it helps, just let me know how to do it.

**Comment by ra3orblade** [comment]
Updates only work for AppImage, this is electron-updater limitation.
