### ISSUE TITLE
Adding summable numbers

### ISSUE THREAD

**Issue by loviuz** [anyproto/anytype-ts#759]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

I would like to have a summable number on grid system, e.g.: I add a column "hours needed" for a task, and I would have a sum of the total hours needed for all filtered tasks.

### Suggested solution

Adding a summable option for the type number :-)

### Alternative

I cannot find other alternatives.

**Comment by ra3orblade** [comment]
Closing as completed.
