### ISSUE TITLE
Extract Content to New Page

### ISSUE THREAD

**Issue by mathias-ewald** [anyproto/anytype-ts#762]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

When I write a page, e.g. to make course notes, I divide my page into multiple sections using headings. As the notes grow, I realize that it would have been better to externalize a section onto it's own page. 

### Suggested solution

Ideally, I right click the heading or select the parts I want to move to their own page and get something like "Externalize to new object" or "Extract to new object" as a menu item. When I click that, I see the new page with the contents. As I return to the previous page, I see that a page link has been inserted.

**Comment by ra3orblade** [comment]
1. Select blocks
2. Click block action menu button
3. Select Turn into object
4. Select type

**Comment by mathias-ewald** [comment]
🤦
