### ISSUE TITLE
Useless Scrollbars

### ISSUE THREAD

**Issue by mathias-ewald** [anyproto/anytype-ts#764]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Despite there is more than enough space to the left and right, I get a scrollbar for a Kanban board that does absolutely nothing of any use.
<img width="2298" alt="Screenshot 2024-06-10 at 21 05 57" src="https://github.com/anyproto/anytype-ts/assets/35083480/09a74e8a-a572-4bdb-88d4-28c739b139fb">

### Expected Behavior

No scrollbar as the Kanban easily fits the screen.

### Steps To Reproduce

1. Create a Set of Tasks
2. Make sure it shows 5 columns or potentially more
3. See the scrollbar

### Environment

```markdown
- OS: MacOS Sonoma
- Version: 0.41.0
```

**Comment by ra3orblade** [comment]
This is fixed in the latest main/alpha/beta versions.
