### ISSUE TITLE
Request to Add CMake Script Language Support in Code Blocks

### ISSUE THREAD

**Issue by mediocrebaby** [anyproto/anytype-ts#765]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

When I insert CMake scripts into Anytype's code blocks, I can't choose CMake to parse.

### Suggested solution

Add CMakeLists option and perform the corresponding parsing work

**Comment by ra3orblade** [comment]
<img width="622" alt="Screenshot 2024-06-11 at 09 08 31" src="https://github.com/anyproto/anytype-ts/assets/1450818/cdf391a2-7855-4208-b7bf-f2561be5c5a0">
Done
