### ISSUE TITLE
Spell-Checking Menu Has Offset

### ISSUE THREAD

**Issue by mathias-ewald** [anyproto/anytype-ts#769]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When I right-click a word that was marked by the spell-checker, the context menu with correction suggestions appears way further down than the word I clicked. The offset is large then the word is further down the document.

<img width="482" alt="Screenshot 2024-06-11 at 19 54 48" src="https://github.com/anyproto/anytype-ts/assets/35083480/967f98b8-878b-40ab-864c-7de9087d0218">

### Expected Behavior

The context menu to appear with its top-left corner hat the exact location of my mouse when I right click the word.

### Steps To Reproduce

1. Misspell something
2. Right-click the word
3. Notice the offset

### Environment

```markdown
- OS: MacOS Sonoma
- Version: 0.41.0
```

**Comment by ra3orblade** [comment]
Check current main/latest alpha, should be fixed.

**Comment by ra3orblade** [comment]
Closing as there are no further comments.
