### ISSUE TITLE
[RFC] Adopt code formatters?

### ISSUE THREAD

**Issue by developomp** [anyproto/anytype-ts#78]
Even though prettier formatter seems to be used by some developers[^1], usage of it does not appear to be enforced (i.e. not part of the linting process). Heck, even the prettier config file itself isn't formatted!

I would like to open some PRs listed below, but I'm not sure if that's something anytype developers are happy with. So I'm asking for confirmation here. Also, this RFC isn't concerned with non-prettifyable files such as shell scripts.

Judging by [`js-anytype.code-workspace`](https://github.com/anyproto/anytype-ts/blob/ee5f69e7d062b0dac1c0d9807183171bc08e838b/js-anytype.code-workspace) and [`.gitignore`](https://github.com/anyproto/anytype-ts/blob/ee5f69e7d062b0dac1c0d9807183171bc08e838b/.gitignore) file, IDEs used by anytype developers are vscode, eclipse, webstorm/intelliJ so I will open PRs based on that assumption (if confirmed).

## PR 1 : Add prettier formatter

- update documentations for setting up formatters for different IDEs
- add eslint husky hook
- remove following lines
  https://github.com/anyproto/anytype-ts/blob/ee5f69e7d062b0dac1c0d9807183171bc08e838b/js-anytype.code-workspace#L18-L24

## PR 2 : Format files affected by prettier

- Simply apply prettier formatting to affected files
- Is done to make diffs more managable and no malicious code slips through the review process
- Anytype developers can verify that no other alterations has been made

[^1]: https://github.com/anyproto/anytype-ts/blob/ee5f69e7d062b0dac1c0d9807183171bc08e838b/.prettierrc.json

**Comment by developomp** [comment]
Sure! What kind of examples are you looking for specifically?

**Comment by developomp** [comment]
Also, IDEs can automatically format the code on file save, so there is literally nothing that has to be done on the developer's side.

**Comment by developomp** [comment]
@ra3orblade bump

**Comment by ra3orblade** [comment]
> > they need a lot of time investment to make the formatting in line with my code compliance
> 
> IDEs can automatically format the code on file save, and prettier provides a CLI tool that can format everything in one go, so there is barely anything that has to be done on the developer's side.

I meant that any automatic code formatting was breaking the code formatting I use, so to make it work correctly you need to waste a lot of time. Like for example spaces between braces in arrays and object deconstructions, I write it like this `[ 1, 2, 3 ]`, `{ key1, key2, key3 }` cause it's more readable and it's not in line with typescript code styles that I've found.

**Comment by developomp** [comment]
Aaah, I see. I will try to make the formatted code as similar to the current code then.

**Comment by developomp** [comment]
[Here](https://github.com/developomp/anyproto-anytype-ts/tree/formatter)'s a rough example of how the formatted code will look like. This is not the final version hence no PR.

You can see how the configs have changed here (f293592728d9f1ce3ef5a025f4e53b4d6d78d543) and the result of `npx prettier . --write` here(1959a8d4dbab6166d112eac03cb79eed0821ac93).

**Opinionated Stuff:**
- Tabs and spaces were being used arbitrarily (sometimes even within the same file), so I made them always use spaces (while trying to conserve tab width).

**Notable things:**
- css/scss files takes up more lines ([example](https://github.com/anyproto/anytype-ts/commit/1959a8d4dbab6166d112eac03cb79eed0821ac93#diff-a32ad1e3c20fb26370f8f3e1d7aab234ee4ec3bffb5f79c359664ad040c2f126))
- long [named imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#named_import) use more lines ([example](https://github.com/anyproto/anytype-ts/commit/1959a8d4dbab6166d112eac03cb79eed0821ac93#diff-b3d4096a52a992826b8c2e142bd573770f5b47692659c074af549aa4dc4dba92), click **Load diff**)
- aligning codes doesn't work ([example](https://github.com/anyproto/anytype-ts/commit/1959a8d4dbab6166d112eac03cb79eed0821ac93#diff-f09e42e26e42639bf17e0a6e611e06a60cc403cd42ac91f56db8a12aa5b016f7))

**Things left to do:**
- consider using https://github.com/trivago/prettier-plugin-sort-imports
- properly set up linting formatting steps to git hook

**Comment by developomp** [comment]
Is there anything you want to add @ra3orblade?

**Comment by ra3orblade** [comment]
- code should use tabs, spaces are there because some developers ignore this rule
- no pretty css formatting pls, such formatting is not human-readable from my POV
- breaking alignment is bad, I've spent some time aligning stuff

thats basically why I do not use automatic formatting =)

**Comment by ra3orblade** [comment]
thanks, it's not critical though, but makes things a bit more readable

**Comment by ra3orblade** [comment]
> > thanks, it's not critical though, but makes things a bit more readable
> 
> Does this refer to the alignment thing?

yep

**Comment by developomp** [comment]
> By the way, this is a really good chance to adopt space indention. The problem with tabs is that their size vary across different programs (and sometimes within the same program). This leads to spacing being ok for some people while being broken for others.

What's your opinion on this?

**Comment by ra3orblade** [comment]
> > By the way, this is a really good chance to adopt space indention. The problem with tabs is that their size vary across different programs (and sometimes within the same program). This leads to spacing being ok for some people while being broken for others.
> 
> What's your opinion on this?

do not have any special opinion on this, I'm used to tabs for like 15 years so it's just a habit.

**Comment by developomp** [comment]
@ra3orblade ready! Review please!
