### ISSUE TITLE
Use a stable version as the latest release

### ISSUE THREAD

**Issue by hellodword** [anyproto/anytype-ts#789]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

https://github.com/anyproto/anytype-ts/releases/latest is redirected to `v0.41.10-alpha`

### Suggested solution

I think `pre-release` is useful here

For example: https://github.com/moby/moby/releases

How do you think?

**Comment by ra3orblade** [comment]
This is not how electron distribution channels work, they use alpha, while github uses rc for release candidates. This is why alpha version is considered full release.
