### ISSUE TITLE
URL relation displayed in Kanban view leads to http://undefined

### ISSUE THREAD

**Issue by aananiev** [anyproto/anytype-ts#796]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Clicking a URL relation displayed on a Kanban card always opens 'http://undefined' 

### Expected Behavior

To open the URL in the value of the relation instead.

### Steps To Reproduce

1. Create a URL relation for an object type
2. Create a set of that object and choose the Kanban Layout
3. Toggle the URL relation to be visible in the cards
4. Create an object of the type, populate the URL relation
5. Open the Kanban view and click on the URL relation that is displayed in the card for that object

### Environment

```markdown
- OS: Windows 11 Pro
- Version: 0.41.1
```

### Anything else?

![image](https://github.com/anyproto/anytype-ts/assets/10808748/7cc1cc04-48cc-44ed-8db5-af5a0fa3ece2)

**Comment by ra3orblade** [comment]
Fixed

**Comment by ra3orblade** [comment]
Check in latest alpha.
