### ISSUE TITLE
Allow inline collections/sets to have editable fields

### ISSUE THREAD

**Issue by uberrice** [anyproto/anytype-ts#80]
In inline collection/set views like this:

![image](https://github.com/anyproto/anytype-ts/assets/15884708/512b2fa9-c952-4312-af20-b5216f0f0751)

it is impossible to change fields 'as you would in excel' by just clicking into a field. Instead, clicking a field opens the item in a popup. It would be preferable to have the fields editable inline - or at least have that as an option.

**Comment by ra3orblade** [comment]
Could you explain? It is possible
![Uploading Screenshot 2023-07-20 at 13.18.10.png…]()

**Comment by uberrice** [comment]
![image](https://github.com/anyproto/anytype-ts/assets/15884708/2bf269b8-fe52-451a-8199-bb9ba4dcf78a)
Adding tags works as expected, yes.

I would expect the same to be possible for the 'Name' column. However, clicking on the name column opens the item in a popup

![image](https://github.com/anyproto/anytype-ts/assets/15884708/f03ddc31-ae58-4418-b077-7087bae29061)

**Comment by uberrice** [comment]
![image](https://github.com/anyproto/anytype-ts/assets/15884708/b9a6c02e-185d-43a1-9b3c-bab7ba68e321)

Not if you do not set a type - and use the default type of 'Note'.

Once i set the type to 'Page' for example I get it:

![image](https://github.com/anyproto/anytype-ts/assets/15884708/0f650a84-6420-400a-8cbc-85886e43ec5f)

I also do not see any way to set a default Type for objects created by the 'New' button.

**Comment by ra3orblade** [comment]
You can't edit *name* of note as note does not have a title, it uses part of text from other blocks as a title, so this is why it works this way.
