### ISSUE TITLE
Text between <> is not pasted

### ISSUE THREAD

**Issue by gio-bon** [anyproto/anytype-ts#801]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When pasting text that contains something between <> into a note, the text does not appear

### Expected Behavior

all text must be pasted

### Steps To Reproduce

When pasting "budegas <infinitas> per que" it appears "budegas  per que"

### Environment

```markdown
- OS: EndeavourOS Linux x86_64 
- Version: 6.6.35-2-lts
```

**Comment by ra3orblade** [comment]
Duplicate https://github.com/anyproto/anytype-heart/issues/1354
