### ISSUE TITLE
Layout is re-adapting to scrollbar or lack thereof upon modal dialog opening

### ISSUE THREAD

**Issue by vintprox** [anyproto/anytype-ts#81]
**Describe the bug**

It's the common UI quirk I observe in web applications that implement image previews and dialogs. Once you're in modal mode, scrollbar vanishes, making the view shake, because scrollbar itself was an important part of layout. It reappears after closing dialog, causing layout re-render.

**To Reproduce**

1. Click on any image in the note or trigger an "Export" dialog.
2. Observe the scrollar on the right disappear, making the entire layout adapt to this.
3. Close the dialog and observe scrollbar reappearing, causing reverse adaptiveness.

**Expected behavior**

Layout should stay intact upon dialog opening. Scrollbar probably should stay "as is" and be besides the dialog, so user doesn't mistakenly think it's a control for scrolling inside the dialog.

**Screenshots or video**

![image](https://github.com/anyproto/anytype-ts/assets/5708819/d6dcf887-349d-412a-abe5-e1ec69011281)
![image](https://github.com/anyproto/anytype-ts/assets/5708819/49f3d4eb-b955-4e7d-8d49-a9f5b976d094)

**Desktop (please complete the following information):**

 - OS: Manjaro, XFCE
 - Version: anytype-bin 0.33.3-1 (AUR)

**Additional context**

This must be happening because you're setting `overflow-y: hidden` on an entire document (`body`), causing scrollbar to disappear when dialog needs to be put before a user, to avoid scrolling on the "back layer". While we're at it, a new problem might present itself if the dialog itself doesn't have scroll behavior: content might overflow and not be seen in its entirety by the user.

I'm not entirely sure if it's even a good idea to apply a global scrollbar, when such desktop SPA can simply make a scrollbar *inside* the designated area, the note itself. But I understand it's because of accessibility reasons. It's just a bit perplexing to see this scrollbar start in the area which should be dedicated to the top menu. But, I suppose, it's worth a separate ticket.

**Comment by ra3orblade** [comment]
https://github.com/anyproto/anytype-ts/pull/82
