### ISSUE TITLE
Printed page shows new vault UI

### ISSUE THREAD

**Issue by ThatOneCalculator** [anyproto/anytype-ts#819]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Physically printing a page shows the new vault layout on the left

### Expected Behavior

Only page contents are shown when printing 

### Steps To Reproduce

1. Create page
2. Ctrl + P
3. Print to printer 

### Environment

```markdown
- OS: Arch Linux
- Version:0.41.18-alpha
```

### Anything else?

Sorry for the crumpled page, as I threw it in the trash out of frustration before realizing I should make a bug report 

![ResizedImage_2024-07-08_16-57-23_1097](https://github.com/anyproto/.github/assets/44733677/d5292ee4-3e5f-4707-a813-22f5d314b87e)

**Comment by ra3orblade** [comment]
Update to the latest alpha, it's already fixed. https://github.com/anyproto/anytype-ts/releases/tag/v0.41.20-alpha
