### ISSUE TITLE
Question regarding long-term roadmap

### ISSUE THREAD

**Issue by poa00** [anyproto/anytype-ts#820]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Less of a feature enhancement suggestion, and more so just a request to gauge the team's outlook with respect to the long-term direction of development.  Namely, I wonder if the notion of converting the desktop clients to native applications a possibility or completely off the table.

### Suggested solution

Native apps can_ be less resource-intensive, more performant and just better overall.

**Comment by ra3orblade** [comment]
We do not have plans for that at this moment.
