### ISSUE TITLE
Ability to hide new navigation bar

### ISSUE THREAD

**Issue by octochamp** [anyproto/anytype-ts#823]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

I'm sure the new navigation bar on the left of v41.21-beta will be useful for people who use multiple spaces, but for those of us to don't it's frustrating that it's not able to be hidden. I often use Anytype in a clean writing mode, full screen with no menu bars or navigation bar and now that's not possible.

### Suggested solution

A similar setting to the ability to hide the old navigation bar and have it pop-out on hover would be ideal.

**Comment by ra3orblade** [comment]
Closing in favor of discussion on forum https://community.anytype.io/t/new-space-sidebar-ctrl-tab-switcher/22529/2
