### ISSUE TITLE
Inline LaTeX equations .

### ISSUE THREAD

**Issue by jon-vfb** [anyproto/anytype-ts#834]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

At the moment we can onlly write LaTeX equations on a 'block' but we cannot embed them inside a test/paragraph.

### Suggested solution

It would be nice to have the ability to write LaTeX equations in a line of text inside a paragraph. I think it would be a good addition, and make math-related notes more aesthetically pleasing to read/write inside anytype.

**Comment by ra3orblade** [comment]
Closing in favour of community feature request https://community.anytype.io/t/inline-latex-addition/2315
Please check this PR, inline LaTeX is working in this branch https://github.com/anyproto/anytype-ts/pull/368
