### ISSUE TITLE
Inline emoji-markup

### ISSUE THREAD

**Issue by BLKFSH** [anyproto/anytype-ts#85]
## Description 

First off this is such a cool project and I'm surprised by all the features, this better blow up soon! I'm loving the built-in emoji-picker as well, but I feel like there could be a faster way to add emojis:

The solution I'm proposing is to just do what Discord does. In addition to their normal emoji-picker you have the option to type a colon, then the name of the emoji and another colon to quickly find and add them. You also get a preview, so when you start typing it gives you suggestions just like the normal search bar in the emoji-picker. So when you type : sob : (without the spaces) it turns into :sob:.  I just noticed GitHub does the same actually so this seems to be somewhat common nowadays! Here's a screenshot of what I mean:
![image](https://github.com/anyproto/anytype-ts/assets/52625640/653912bc-41ef-4757-a051-e8dccf33fe6d)

I could also imagine some automatic suggestions for emojis based on the words you've written, but that might get a little annoying - might work well for suggestions in the actual picker, though!

Anyway, I hope I didn't miss some way to actually do this already, I'm a bit overwhelmed by the massive amount of features this project already has, so thank you very much!

**Comment by ra3orblade** [comment]
Please create a feature request at community.anytype.io
