### ISSUE TITLE
[Feature request] Action layout type icon in graph mode

### ISSUE THREAD

**Issue by 22Xy** [anyproto/anytype-ts#855]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Currently for Action layout type, if the checkbox is unchecked, it's still a static checked icon in graph mode for the node. I think it would improve the user experience in graph mode if the checked status is synced. Otherwise, the user need to hover on each action type node to see the actual status.

![image](https://github.com/user-attachments/assets/9941b2c6-23c7-418c-8098-c0612b160ac5)
![image](https://github.com/user-attachments/assets/f741f23b-b38c-43be-a43a-50823aebee34)
![image](https://github.com/user-attachments/assets/e26c26b5-c6a5-401b-af50-ab6595c220c0)

### Suggested solution

Fetch the actual status in graph mode and dynamically show checked/unchecked icons. I can help implement it but it would be more efficient if someone can guide me which file(s) to start with :)

**Comment by ra3orblade** [comment]
Done.
