### ISSUE TITLE
Latex feature - alignment left not woking

### ISSUE THREAD

**Issue by m0hi1** [anyproto/anytype-ts#865]
### Current Behavior

Latex are not aligned left properly or default there always space at the start.
![image](https://github.com/user-attachments/assets/91083a39-958c-4351-829f-7500f14e6fd1)

### Expected Behavior

Should be left properly and container block have some padding less than text.
![image](https://github.com/user-attachments/assets/f0b278d5-6e70-4b26-a2b4-3aa882e4ff11)

### Steps To Reproduce

Simply start anytype on any platform supported.
Type mathematical equation.
/ for options

### Environment

```markdown
OSs: Windows 11
    Linux fedora 40 or Ubuntu 24.04
```

**Comment by ra3orblade** [comment]
This is a fleqn option in KaTeX, it was contributed by @LavaCxx set to true, as I'm googling it is required for amsmath LaTeX.

**Comment by ra3orblade** [comment]
Closing, no response.
