### ISSUE TITLE
$ without closing shows as math

### ISSUE THREAD

**Issue by ThatOneCalculator** [anyproto/anytype-ts#870]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

In 0.41.44, a sentence like `$30 per, $100 for 4-pack (might do 2 for me 2 for parents)` tries to be a math equation

![image](https://github.com/user-attachments/assets/c632d5cf-0e19-4a73-ada5-7b09f3eaecb5)

### Expected Behavior

$ without closing just shows as a dollar sign. This behavior was fine before the latest beta update.

![image](https://github.com/user-attachments/assets/73799c80-820c-4642-8430-763b35eaf0c9)

### Steps To Reproduce

1. Write any sentence like that

### Environment

```markdown
- OS: Linux
- Version: 0.41.44
```

**Comment by ra3orblade** [comment]
Fixed.
