### ISSUE TITLE
PIN Input Field Displays Plaintext Instead of Asterisks or Dots when i type

### ISSUE THREAD

**Issue by redcatsec** [anyproto/anytype-ts#883]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When entering a PIN in the app, the digits are displayed as plaintext instead of being masked by asterisks or dots. This exposes sensitive information to anyone who might be observing the screen.

### Expected Behavior

the digits are displayed as plaintext instead  when i type.

### Steps To Reproduce

activate the pin and type your pin

### Environment

```markdown
- OS: MacOS
- Version: ARM M1
```

**Comment by ra3orblade** [comment]
I do not understand the problem, video pls. They become bullets with delay like on iOS as was requested by the product team.

**Comment by ra3orblade** [comment]
Closing, no response.

**Comment by redcatsec** [comment]
https://github.com/user-attachments/assets/00c36321-8dda-4cbf-97c0-24006a85fc6d

Sorry for delay Answer. 
the first type in get the issue , the secound one shows how i always expect.

**Comment by redcatsec** [comment]
@ra3orblade  i still see this issue
anything new on this  issue

**Comment by ra3orblade** [comment]
It was requested to work like this from the product team so I can't really give any news on the issue as it is working as expected.
