### ISSUE TITLE
The code in the table is automatically converted to unexpected text

### ISSUE THREAD

**Issue by jlhg** [anyproto/anytype-ts#896]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When I type

```text
(^\w+.$)|(^\w+$)
```

or

```text
/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/
```
 in the table, they are converted to unexpected text.

https://github.com/user-attachments/assets/8d283e30-068e-4efa-bf5e-698fef49c5db

### Expected Behavior

The code text should remain in its original display.

### Steps To Reproduce

1. Type `(^\w+.$)|(^\w+$)` and convert it to code in the table.
2. Click the area outside the table.

### Environment

```markdown
- OS: Windows 11
- Version: 0.42.4
```

**Comment by ra3orblade** [comment]
Already fixed, it's a problem with inline latex parsing.

**Comment by ra3orblade** [comment]
Closing as completed, no answer for 3 weeks.

**Comment by jlhg** [comment]
This issue still exists in version 0.43.0.
