### ISSUE TITLE
Add support for Omnivore Integration

### ISSUE THREAD

**Issue by Nexus-Gits** [anyproto/anytype-ts#898]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

[Omnivore](https://docs.omnivore.app/) is a Read it later app with RSS feed functionality. They have plugin support like [obsidian](https://github.com/omnivore-app/obsidian-omnivore) and [logseq](https://github.com/omnivore-app/logseq-omnivore). Please Add support for Omnivore Integration for Omnivore.

### Suggested solution

Please Add support for Omnivore Integration for Omnivore.

**Comment by ra3orblade** [comment]
Create a feature request at https://community.anytype.io/ please.
