### ISSUE TITLE
Improved conversion from URL → Bookmark

### ISSUE THREAD

**Issue by KhalilSantana** [anyproto/anytype-ts#90]
## Description 

Pasting URLs trigger a "Create bookmark" action, which is great as it creates a "card" that you can easily see the URL's Title and a snippet of the website itself. However, right-clicking "Turn into Object → Bookmark" doesn't create the card, only changes the font of the URL.

**Describe the solution you'd like**
Adapt the current "Turn URL into bookmark" logic, so it copies the behavior of pasting a URL and selecting the "Bookmark" type.

**Describe alternatives you've considered**
If that's somehow not viable to do automatically, then at least a "refresh" option to fetch the contents again

**Comment by ra3orblade** [comment]
Please create a feature request at https://community.anytype.io
