### ISSUE TITLE
Interface elements are hidden

### ISSUE THREAD

**Issue by i-iooi-i** [anyproto/anytype-ts#907]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

![PixPin_2024-08-25_21-40-45](https://github.com/user-attachments/assets/4649b006-31aa-4686-ae0b-91e296c1aa2a)

I used Anytype for the first time, but I found that there were too many distracting elements on the win system, and I wanted it to look clean on the page, and decided what to display according to the user's needs.

For example, hide the scrollbar on the screen, and hide the help buttons and tool below.

### Suggested solution

I want to be able to customize the interface elements more flexibly.
With some settings , let the user decide what content to show, thank you very much.

**Comment by ra3orblade** [comment]
Create a request on forum please, https://community.anytype.io/c/feature-requests/6/none.
