### ISSUE TITLE
Rounded icon for 32x32

### ISSUE THREAD

**Issue by ZMensRain** [anyproto/anytype-ts#909]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Currently the app icon for 32x32 size is not rounded. When using the extension dash-to-dock on Fedora with gnome, it by default uses the 32x32 icon size for all apps and the anytype icon looks terrible in the dock.
![Screenshot from 2024-08-26 12-47-50](https://github.com/user-attachments/assets/aa962ca5-0f9c-481d-a9ee-28e585cdf367)

### Suggested solution

There is a simple fix, just round the corners I was able to do this myself and I think it looks much better
![Screenshot from 2024-08-26 12-45-45](https://github.com/user-attachments/assets/b50545ba-d75a-498a-a9c7-f0ab81dfeb36)
Here is the file I used if that helps
![32x32](https://github.com/user-attachments/assets/5ecb92f0-15a9-48cd-ac10-02e94b02b149)

**Comment by ZMensRain** [comment]
#920 was merged

**Comment by ZMensRain** [comment]
I think I messed up, I think the file in electron/img/icons/32x32.png also has to be replaced. Should I create another pull request? And are there any other files that might need replacing to make the build have the right icon?

**Comment by ra3orblade** [comment]
It is used in Windows tray, Idk if it has to be rounded.

**Comment by ra3orblade** [comment]
Closing as implemented.
