### ISSUE TITLE
Enable the usage of emoji as the icon for the space on the sidebar

### ISSUE THREAD

**Issue by jonathanim88** [anyproto/anytype-ts#918]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

![imagem](https://github.com/user-attachments/assets/e5b525be-afa1-4dac-a78d-f792dce8fdf5)

the default board images are pretty but very non descriptive, I often find myself  switching through boards as it's  faster than hovering the tooltip

### Suggested solution

Being able to use an emoji as the icon for the Space would be great as an indicator of that board and easy to use in day to day activities

![imagem](https://github.com/user-attachments/assets/bb9f8351-a028-4379-a316-2dbaaa026b9e)

**Comment by yasyuk** [comment]
Hello,
We have intentionally limited the use of emoji for space icons. First, we don't want them to look like objects or types. Also, we think it's important that users upload their own images as space icons.

**Comment by ra3orblade** [comment]
> Hello, We have intentionally limited the use of emoji for space icons. First, we don't want them to look like objects or types. Also, we think it's important that users upload their own images as space icons.

Closing.

**Comment by payne747** [comment]
Would be good to get some documentation on recommended sizes for the icon so they properly fit in the spaces side bar.
