### ISSUE TITLE
Search is important for note

### ISSUE THREAD

**Issue by kinglion580** [anyproto/anytype-ts#93]
## Description 

**Is your feature request related to a problem? Please describe.**
Search is only can search object, actually most of time, user want to search blocks. 
![image](https://github.com/anyproto/anytype-ts/assets/10623730/021eb1e0-9073-491a-ad46-e60228eaada3)

**Describe the solution you'd like**
The user can search content, and in the result it will show context. Also we can have advance search. I'd like the search like notion.
detail -> https://community.anytype.io/t/full-document-search-and-with-context-shown-in-the-search-field/2130
![image](https://github.com/anyproto/anytype-ts/assets/10623730/134eb036-9294-4db2-8063-543b49ca68e6)

**Comment by ra3orblade** [comment]
I do not understand the description.

**Comment by kinglion580** [comment]
Sorry for the confusing, I have updated the description.

**Comment by ra3orblade** [comment]
now i've got it, yes we will be working on that but later, right now we are focused on multiple spaces and collaboration.

**Comment by jav-ed** [comment]
any update on this?

**Comment by ra3orblade** [comment]
No update yet, we now have technical solution that allows us to show this logic, but we didn't make client support yet, but this will be definitely implemented, we have this in our tracker.

**Comment by jav-ed** [comment]
Thank you for the kind and fast reply, looking forward to inshallah seeing this feature implemented
