### ISSUE TITLE
Anytype not working on Ubuntu

### ISSUE THREAD

**Issue by dada878** [anyproto/anytype-ts#95]
**Describe the bug**
Anytype not working on Ubuntu.

**To Reproduce**
1. Download the app
2. Enter the recovery phrase 
3. Login success, but there is just a blank page

**Expected behavior**
I can view and use Anytype.

**Screenshots or video**
That is Ubuntu, but with MacOS Theme.
![Screenshot from 2023-07-23 00-39-47](https://github.com/anyproto/anytype-ts/assets/37009584/979b5662-44a9-4273-aea0-c9c2d1a508f8)

**Laptop:**
 - OS: Ubuntu 22.04.2 LTS
 - Version: Debian latest form https://anytype.io/

**Comment by developomp** [comment]
I can not replicate the issue on a VM. Can you provide logs?

Tested on:
- Ubuntu 22.04.2
- Anytype debian package 0.33.3

**Comment by ra3orblade** [comment]
Console logs both from terminal and devtools would help a lot.

**Comment by emielbeinema** [comment]
I cannot replicate this issue on a (non-VM) system running Ubuntu 23.04 and Anytype 0.32.3. It seems to be working fine (except for not storing my login information, but that is a different issue, if one at all).

**Comment by dada878** [comment]
![Screenshot from 2023-08-01 14-11-08](https://github.com/anyproto/anytype-ts/assets/37009584/4514738c-5bd6-4591-966f-98a2c9761103)

**Comment by developomp** [comment]
So,

**1**: `WalletRecover` function is failing for some reason:
https://github.com/anyproto/anytype-ts/blob/b81b1ca0b885640f23df043b3ac585d6576edc37/src/ts/lib/api/command.ts#L55

**2**: `this.refPhrase` is null in here:
https://github.com/anyproto/anytype-ts/blob/b81b1ca0b885640f23df043b3ac585d6576edc37/src/ts/component/page/auth/login.tsx#L79

@dada878 sorry for asking this, but can you try authenticating again with the phrases in your phone? You can find the code in `Home > Your Profile Icon (bottom) > Profile > Recovery Phrase`.

**Comment by dada878** [comment]
It's works, thanks.

**Comment by fuksman** [comment]
@dada878 can we close the issue then?

**Comment by dada878** [comment]
ok
