### ISSUE TITLE
cursor: pointer

### ISSUE THREAD

**Issue by negue** [anyproto/anytype-ts#97]
## Description 

**Is your feature request related to a problem? Please describe.**
Currently many controls/blocks (that are clickable) have no `cursor: pointer` on it.

**Describe the solution you'd like**
Add `cursor: pointer` to a bunch of elements 😬   

**Additional context**

If allowed - I'd like to create a PR for it as well, so that this task not stops the other importing things to do 😬

**Comment by developomp** [comment]
@negue are you working on a PR for this? If not, I will start working on it.

**Comment by negue** [comment]
I did start on a few places but sure not all found / changed yet

just wanted to know if its already allowed to do PRs, I read somewhere that "PR not acvepeted yet" hence the question   😁

**Comment by fuksman** [comment]
@negue, yes, we're accepting PRs in this repo since today :)

**Comment by negue** [comment]
Awesome! Thank you - then I'll start creating them 😬

**Comment by ra3orblade** [comment]
Removing `cursor:  pointer` was a design decision, @sebyakin can explain the logic behind it.

**Comment by negue** [comment]
Oh, I see, I just thought its counter intuitive for desktop / mouse users not knowing which button / block is clickable. 

Will wait for the response, if all elements stay like that or only a list of specific ones

**Comment by sebyakin** [comment]
Hello Negue, 
Thnak you for your comment. 

For the desktop application, we're embracing a more native-like experience. Traditional desktop software doesn't utilize cursor alterations to denote interactive components, as changing cursors is primarily a web design pattern.

**Comment by negue** [comment]
Oh, I see - I never thought that there is (should) be a difference with web and native controls

As long all clickable elements have some kind of "known" indicator that its clickable a different solution could be possible as well.

I'll also add some more examples to the #100 which could have more hover/visual feedback that those are clickable since its probably the way to mark those instead of demanding "cursor pointer here pls" xD
