### ISSUE TITLE
Allow for opening a new window from the tray icon

### ISSUE THREAD

**Issue by arran4** [anyproto/anytype-ts#981]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

When multiple virtual desktops are being used, sometimes you want to open a new window rather than be forced back to the virtual desktop where you were last using anytype.

Currently on KDE plasma when you open any type from the tray it takes you back to the previous window, which then you open a new window from it then move that back to the virtual desktop you're intending to work on. 

### Suggested solution

It would be nice if it were to open a new window, similar like if you were to try open your webbrowser

**Comment by ra3orblade** [comment]
Available in https://github.com/anyproto/anytype-ts/releases/tag/v0.42.38-beta
