### ISSUE TITLE
Arch AUR is broken

### ISSUE THREAD

**Issue by rothcold** [anyproto/anytype-ts#991]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

https://aur.archlinux.org/packages/anytype-electron-bin

AUR source using a removed version of release. https://github.com/anyproto/anytype-ts/releases/download/v0.42.33-beta/anytype_0.42.33-beta_amd64.deb

### Expected Behavior

Use the correct source link of latest version.

### Steps To Reproduce

1. yay -Syy anytype-electron-bin
2. Cannot download the source of anytype

### Environment

```markdown
- OS:ArchLinux
- Version: Latest
```

**Comment by ra3orblade** [comment]
AUR package is maintained by community, create a post on https://community.anytype.io please.

**Comment by rothcold** [comment]
> AUR package is maintained by community, create a post on https://community.anytype.io please.

Got it. Thanks.
